{
 "title": "Kafka Streams - RocksDb Memory",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_streams_stream_state_metrics_number_open_files, namespace)"
    }
   },
   {
    "name": "thread_id",
    "label": "Thread",
    "query": {
     "query": "label_values(kafka_streams_stream_state_metrics_number_open_files, thread_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Healthcheck",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total block cache capacity",
     "type": "stat",
     "description": "The capacity of all block cache in your application.\n",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_capacity{ }"
      }
     ]
    },
    {
     "title": "Total block cache usage",
     "type": "stat",
     "description": "The memory size of the entries residing in all block cache in bytes.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_usage{ }"
      }
     ]
    },
    {
     "title": "Total block cache pinned usage",
     "type": "stat",
     "description": "The memory size for the entries being pinned in all block cache in bytes.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_pinned_usage{}"
      }
     ]
    },
    {
     "title": "Total size of all memtables",
     "type": "stat",
     "description": "The approximate size of active, unflushed immutable, and pinned immutable all memtables in bytes.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_size_all_mem_tables{}"
      }
     ]
    },
    {
     "title": "Number immutable memtables",
     "type": "stat",
     "description": "The number of immutable memtables that have not yet been flushed.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_num_immutable_mem_table{}"
      }
     ]
    },
    {
     "title": "Total size of all SST files",
     "type": "stat",
     "description": "The approximate size of active and unflushed immutable all memtables in bytes.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_total_sst_files_size{}"
      }
     ]
    },
    {
     "title": "Total number of keys",
     "type": "stat",
     "description": "The total estimated number of keys in the active and unflushed immutable memtables and storage.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_estimate_num_keys{}"
      }
     ]
    },
    {
     "title": "Compaction pending",
     "type": "stat",
     "description": "This metric reports 1 if at least one compaction is pending, otherwise it reports 0.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_compaction_pending{}"
      }
     ]
    },
    {
     "title": "Memtable flush pending",
     "type": "stat",
     "description": "This metric reports 1 if a memtable flush is pending, otherwise it reports 0.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_mem_table_flush_pending{}"
      }
     ]
    },
    {
     "title": "Number of background errors",
     "type": "stat",
     "description": "The total number of background errors.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_background_errors{}"
      }
     ]
    }
   ]
  },
  {
   "title": " RocksDb Metrics (by thread)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total block cache capacity",
   "type": "stat",
   "description": "The capacity of all block cache in your application.\n",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_block_cache_capacity{ thread_id=\"$thread_id\"}"
    }
   ]
  },
  {
   "title": "Total block cache usage",
   "type": "stat",
   "description": "The memory size of the entries residing in all block cache in bytes.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_block_cache_usage{ thread_id=\"$thread_id\"}"
    }
   ]
  },
  {
   "title": "Total size of all memtables",
   "type": "stat",
   "description": "The approximate size of active, unflushed immutable, and pinned immutable all memtables in bytes.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_size_all_mem_tables{thread_id=\"$thread_id\"}"
    }
   ]
  },
  {
   "title": "Total number of keys",
   "type": "stat",
   "description": "The total estimated number of keys in the active and unflushed immutable memtables and storage.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_estimate_num_keys{thread_id=\"$thread_id\"}"
    }
   ]
  },
  {
   "title": "Number of keys in active & unflushed storage",
   "type": "graph",
   "description": "The estimated number of keys in the active and unflushed immutable memtables and storage.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_estimate_num_keys{ thread_id=\"$thread_id\"}",
     "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
    }
   ]
  },
  {
   "title": "Estimate pending compaction bytes",
   "type": "graph",
   "description": "The estimated total number of bytes a compaction needs to rewrite on disk to get all levels down to under target size (only valid for level compaction).",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_estimate_pending_compaction_bytes{ thread_id=\"$thread_id\"}",
     "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
    }
   ]
  },
  {
   "title": "RocksDb background errors",
   "type": "graph",
   "description": "The total number of background errors.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_background_errors{ thread_id=\"$thread_id\"}",
     "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
    }
   ]
  },
  {
   "title": "RocksDB Metrics - Memtable (by thread)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Size All MemTables",
     "type": "graph",
     "description": "The approximate size of active, unflushed immutable, and pinned immutable memtables in bytes.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_size_all_mem_tables{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Active size memtable",
     "type": "graph",
     "description": "The approximate size of the active memtable in bytes.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_cur_size_active_mem_table{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Number of entries in active memtable",
     "type": "graph",
     "description": "The number of entries in the active memtable.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_num_entries_active_mem_table{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Number of immutable memtables yet not flushed",
     "type": "graph",
     "description": "The number of immutable memtables that have not yet been flushed.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_num_immutable_mem_table{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Number of entries in unflushed memtable",
     "type": "graph",
     "description": "The number of entries in the unflushed immutable memtables.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_num_entries_imm_mem_tables{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Number of delete entries in active memtable",
     "type": "graph",
     "description": "The number of delete entries in the active memtable.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_num_deletes_active_mem_table{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Number of delete entries in unflushed memtable",
     "type": "graph",
     "description": "The number of delete entries in the unflushed immutable memtables.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_num_deletes_imm_mem_tables{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDb Metrics - Block cache (by thread)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Block Cache Usage",
     "type": "graph",
     "description": "The memory size of the entries residing in block cache in bytes.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_usage{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Block Cache Pinned Usage",
     "type": "graph",
     "description": "The memory size for the entries being pinned in the block cache in bytes.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_pinned_usage{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Block Cache Capacity",
     "type": "graph",
     "description": "The capacity of the block cache in bytes.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_capacity{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDb Metrics - SST files (by thread)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total SST files",
     "type": "graph",
     "description": "The total size in bytes of all Sorted Sequence Table (SST) files.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_total_sst_files_size{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Live SST files",
     "type": "graph",
     "description": "The total size in bytes of all Sorted Sequence Table (SST) files that belong to the latest log-structured merge (LSM) tree.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_live_sst_files_size{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Estimate memory used for reading SSTs",
     "type": "graph",
     "description": "The estimated memory in bytes used for reading Sorted Sequence Tables (SSTs), excluding memory used in block cache.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_estimate_table_readers_mem{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Number live versions of LSM Tree",
     "type": "graph",
     "description": "Number of live versions of the log-structured merge (LSM) tree.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_num_live_versions{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDb Statistics (by thread)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bytes Written Rate",
     "type": "graph",
     "description": "The average number of bytes written per second to the RocksDB state store.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_bytes_written_rate{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Bytes Read Rate",
     "type": "graph",
     "description": "The average number of bytes read per second from the RocksDB state store.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_bytes_read_rate{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Memtable Flushed Rate",
     "type": "graph",
     "description": "The average number of bytes flushed per second from the memtable to disk.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_memtable_bytes_flushed_rate{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Block cache data hit ratio",
     "type": "graph",
     "description": "The ratio of block cache hits for data blocks, relative to all lookups for data blocks to the block cache.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_data_hit_ratio{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Block cache filter hit ratio",
     "type": "graph",
     "description": "The ratio of block cache hits for filter blocks, relative to all lookups for filter blocks to the block cache.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_filter_hit_ratio{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Block cache index hit ratio",
     "type": "graph",
     "description": "The ratio of block cache hits for index blocks, relative to all lookups for index blocks to the block cache.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_index_hit_ratio{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Memtable hit ratio",
     "type": "graph",
     "description": "The ratio of memtable hits, relative to all lookups to the memtable.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_memtable_hit_ratio{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Number of open files",
     "type": "graph",
     "description": "The number of current open files.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_number_open_files{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    },
    {
     "title": "Number of error files",
     "type": "graph",
     "description": "The total number of file errors that occurred.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_number_file_errors_total{ thread_id=\"$thread_id\"}",
       "legendFormat": "{{rocksdb_state_id}}{{rocksdb_window_state_id}}{{rocksdb-session-state}}-{{task_id}}"
      }
     ]
    }
   ]
  }
 ]
}