apiVersion: v2
name: ladmesp
version: "1.0.1"
appVersion: "1.0.0"
# Disabling kubeVersion because GKE is dumb
# kubeVersion: ">=v1.11.0"
description: A Helm chart for LSDMESP
keywords:
  - lsdmesp
  - kubernetes
  - kafka
home: https://github.com/lsdopen/charts
sources:
  - https://github.com/lsdopen
maintainers:
  - name: LSD
    email: support@lsdopen.io
    url: https://lsdopen.io
deprecated: false
tillerVersion: ">=v3.2.1"

dependencies:
- name: cp-helm-charts
  version: "0.6.1"
  repository: https://confluentinc.github.io/cp-helm-charts/
- name: kafka-manager
  version: "2.3.2"
  repository: https://charts.helm.sh/stable/
- name: kafka-connect-ui
  version: "0.1.0"
  repository: https://gradiant.github.io/charts/
- name: schema-registry-ui
  version: "0.4.4"
  repository: https://charts.helm.sh/stable/
- name: kafka-topics-ui
  version: "0.3.0"
  repository: https://dhiatn.github.io/helm-kafka-topics-ui/
- name: akhq
  version: "0.2.1"
  repository: https://akhq.io/
