lsdmesp:
  ldap:
    readOnlyUser:
      password: h.HJoGat34{P
  confluent:
    connect:
      password: o3taHPhG.J4{
    controlcenter:
      password: G3.PoHh4Jta{
    kafka:
      password: 3a4toHJ.GhP{
    kafkarestclass:
      password: H{.JhPGa43to
    kafkarestproxy:
      password: 3JhPoG.a4t{H
    ksqldb:
      password: Jto{GP4H3.ah
    schemaregistry:
      password: toaPH{4.G3hJ
  tls:
    ca:
      cert: |
        -----BEGIN CERTIFICATE-----
        MIIDtTCCAp2gAwIBAgIUG3CYY5VHt+rDq0jb+mDEBJcnpfUwDQYJKoZIhvcNAQEL
        BQAwajELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRUwEwYDVQQHDAxNb3VudGFp
        blZpZXcxEjAQBgNVBAoMCUNvbmZsdWVudDERMA8GA1UECwwIT3BlcmF0b3IxEDAO
        BgNVBAMMB0xvY2FsQ0EwHhcNMjQwNDE2MTc0NDIyWhcNMzQwNDE0MTc0NDIyWjBq
        MQswCQYDVQQGEwJVUzELMAkGA1UECAwCQ0ExFTATBgNVBAcMDE1vdW50YWluVmll
        dzESMBAGA1UECgwJQ29uZmx1ZW50MREwDwYDVQQLDAhPcGVyYXRvcjEQMA4GA1UE
        AwwHTG9jYWxDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALuEQCBe
        62rc0sgMNDTaavl3MOGHXl8LBJs6tfcm7vjg5jcdQhsGo/Xk0UJaxCgFTvzsBX8R
        rL4YZsQGZHl4oGZx0Hf821/gC+wZ1bTklU93JqzohKGkC2Qngus4BP8uasCq3gPI
        J3MmvZl9ezrou2YX4XI6drrO8pt3n6IsAafwPNjvXmiBPGEtD/g0se9C2uumLuss
        0TpaCq0vIoC8c+O2IwbdA5Qbo4CWeL3jZp4g4ULgYXjAy9aUuPbCW/hxwk3+0n5i
        TMtbSajqK8KOP+1m8Ltp27iHeaViQf9wphOhZwLJTdykVXO0sbLZFbELVy3y9ich
        pAURzM8N/8UGQEECAwEAAaNTMFEwHQYDVR0OBBYEFAJU0npP3CibD2E03QcRm2gl
        UVSqMB8GA1UdIwQYMBaAFAJU0npP3CibD2E03QcRm2glUVSqMA8GA1UdEwEB/wQF
        MAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJyNu2xTCOvEj71qg/OF/7QXjNo4eimz
        SN3GeyqA4IhsStSYpzaWBVC7Jv+2jvQZpRZqfpb1SdoUf78Mg0+o2WUh6Agf7b6l
        ZVt8RcvHzjNvlj5WUCs+Jj2TQsA0iveTcA+PVPwu0gT6AMx4v9qOyqFdSPmSQoja
        4RLLIvn9GoomscM5DlvPQQ7eooDFZ+h2GFyhgEEmkbMeI/cT2r7MBv10oCxhX2WM
        t0Av7Nd8dyTdmkFzFE4cAzjebFAmA/rKVEQdr3JgIW4Yku8+U8E9xr/nDq+7uEsq
        OoPROCWtwSmPpNQqZLefErMkBpHwCEMZ5yYrwRguH8yFwW7GcdkvJMg=
        -----END CERTIFICATE-----
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC7hEAgXutq3NLI
        DDQ02mr5dzDhh15fCwSbOrX3Ju744OY3HUIbBqP15NFCWsQoBU787AV/Eay+GGbE
        BmR5eKBmcdB3/Ntf4AvsGdW05JVPdyas6IShpAtkJ4LrOAT/LmrAqt4DyCdzJr2Z
        fXs66LtmF+FyOna6zvKbd5+iLAGn8DzY715ogTxhLQ/4NLHvQtrrpi7rLNE6Wgqt
        LyKAvHPjtiMG3QOUG6OAlni942aeIOFC4GF4wMvWlLj2wlv4ccJN/tJ+YkzLW0mo
        6ivCjj/tZvC7adu4h3mlYkH/cKYToWcCyU3cpFVztLGy2RWxC1ct8vYnIaQFEczP
        Df/FBkBBAgMBAAECggEACsy6nsKov15Ze3EMfrDHsXd2Zr7Tphit2rzeZw4kfEwD
        pk/2kzTmM47KqI4utvlbS8DSLjfX4ZjpLkgJ+F8EqfHLJmX3QoXWWfJA9yqlGM8N
        eK7pmJ+okkueRCrVStcjCdatc71O3FhyWgk6lDF8PYyJjPkmBmtN2Ltig8YSEFhy
        A9ozVdtdJwB1k+uWQ1WaLyaveWbzd1iY+T3MfkimJKah6cwG8fPZMMTbSIT6Mrs3
        ENOQQTJNpyfRhKtj3HluEwzoni2bsC2DOk82D+PcIUjV6A2BGq9UFU24sr2cIN50
        NB9z8F2Qhs/Z4rCWnLXQrD/ZfRVynME+BUPpD/4dYQKBgQDbJjHFXa8QBVWI+42O
        1tdJ2EOMdXrVZIkpoq3CHl0vaCIfhQWP95TYSwL2p2LBe5bePZmtAPX+8NdGCWLi
        M53JzJ0qHQDe0DYKIaSo9/evwJzx1wDB6kUaLgJiVg2oxYKRi+WKOshRlW8MbRVG
        hV4xIQxLKr9DvF58+rRmZzZf6QKBgQDbDFrVgMlbB80LDCxdMQycysFOyx/D3FKa
        lVJb3k9eKuIkX1t81jl3GaE0eOWV7aSCusNknzpHUlyEbTFR1Hm6ag0jX11NK0Cw
        bsqW5OiyNmwda59zY0Wtlw+0xA3p6Lf5eTgQjnYvdAjlbkqN3sT2bxL5dlXZb+De
        3m0tiJi+mQKBgQCCZhOvcLM+QS5IOAZfPA8WbYykAzN3zj6fe6EQpKimELxdLPXG
        WHdEzD2TLr5gin2W9+h9PNkjPYOatPMVzcjRzuKlsGRYMGQ3WxVzRTkoZt/8NwbI
        W/GKRl48zR+LkRrEKA4JVjjj8psFNdM3Bxyo9xUtlN4CHA/NJhA57qg4IQKBgHcZ
        K5YkNNbC0hBsqP5uec4SS7J8rKPAekVEZQhAQmUP6e8ezc59Z7dC/yxZg3LWR/kw
        dKaUEIrQ1C7Ic+VrIlhh6wzNgBxCJSUIyCvtADxNbNE+P+7sDemJVefSJUKF3unM
        p9gQrV+1tlSQeAbVFcBruiRa2+iidOCYjUIRoAMZAoGBALYKfZGxP1CZUMpGTupJ
        Nl7gV1mtME0cVXo4XIlw0pC/pLNc/S1sd+BfxnNFdCSosByNgjQN6roIijzsgzyS
        W1qXVxWulDPbpyVTab8fNBxfWZs5dGO6dAnqfttCtGegHHANrO8ven3G5WuMXLQe
        IDPVf7vDR+MFN1EblRlOTqg1
        -----END PRIVATE KEY-----
    mds:
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCdw0ZfNC1tLGIW
        HS9/KRkWM0aD2Yb13Pi5NTyc/D3rdJkCCVVyzPc3xehge/cpmvFg5/jRRMBv+LyD
        0RUdkf0i+IPkFelHuRRJ7olnOFHEge/F8mdUW/2ctxgUqFkBMi6zgRLSvYaG20dm
        9RaTPQPrtJyw0ekvS2ZY8TJ6uOD7XtDlQR4neei+0Kz11TjfiRv1CjR/l98hSnLh
        DkFe1Xy4mJEyCCjQ8fUDAagS9pTzrn0xeoNkXcG+1p2CUpx69x6VPonBlhCSMG7V
        T6oWNoTuQt3mqDUfz8NG4noch/LJsh2EZZOJTUeWxcZWzK0zuWC6uA5aYkmm3mcT
        Uys2AfzHAgMBAAECggEAAZlle44+Lk7L3mjZ/rz+PxuynvWJM7F+Ep/ihxOGK9PZ
        FTczrDU9sE1g8fwaYPaWyc0FgwGNEyrUpmAWibUyzrRG31IFilpARWZAnaY+1fIc
        lHIaRWBQAtMBpdFLDa23jCRGej0SQbMJV0GBbWlUl9gTL+EA2co24GHu3rrvCj1D
        Zsd3VWBdxIs53Gdw6e4aDoxpA8VDKuKeqm1b+yBkd8DGsOJ2Quchk9XDlndyB5bX
        TBQeYuq+4C6LZNQpAdQkwEs+RM9BHM6d1oVebT9CINQ1ugQKbl3y6J/b4U1btiap
        QAeqh20TSGUDHdRrQf+nI83ehkZEg/jLBQMd3ppqGQKBgQDSC7tNHhaXdDhPBpoa
        wp4RtKAUBXKSMHYbS3hljIxeNjtxAkeKOuLxB2KiDE8E/FPrWDtrDI+hHl3gc+PF
        Pao5ficuqc5JIDxvvaTuWnzJ2Q8A7GC0LmPIyeDV6N5dKJYBn4/q5vD5XkvQ3Vzf
        b/7jwC2r0G+xkYPOgWzvrVMONQKBgQDAR0UI2C3Ts8w7pw3oyrRTWIL1HrYWSvRe
        40moxKeOt9VP1/ZiM+Z/TrmUAJrIeH7WFhmJfkoIYLonhpOj/guMKbf1Nkc7J46H
        lNNX8pD+/7/qgaBY1o7PfmFmGT0KELeioMniBAGamHFpp1gBwRDAwJs2rqLHhHjp
        0zpIvmTuiwKBgAWbBIuhUu8Fzf7l6TTvnrJQRLlkD9Ow8WX3FKZ5IsHc5qc0bV5W
        BfpyvQIgG/fBGCg+uY84zZh6K/0yepCn/aP9JuSK6ZNwBczhncYyqgPlBA59QHNu
        jYEtSg/LYCvSSnaOoJOfSC0PhCx1y+W2onHHjjB4ppJxlLftIlAfKwlFAoGAOZGd
        I8bGAcqlbX7Y9UgrsYCgxQ9K6WXLwNVAap1mpZ546Yz5ofF0I83IVn3P2hHpt+Oq
        BbagJ93+HnN2pPUdM/wRrgNwVE/FpuZyWLSxoQelyGrDPZYP8CQguVb5JZhXwwNt
        LpSQfl8CJeYKvYu2nl+MmVS0PBR3t1qc6sbGpX0CgYEAvDUEiAZXIALqhbt3gptU
        C4Lxfe3xjhoNWdV2+J6k3FFEVUZc+BLfphuX9uAj1ogaLNVi7jZjzBPFRaXzb1kt
        ByvTxaRqagKrbrBsNeLV7uwjoomHYwDLa5ufusYqTxeeU0MN015UKa21XOMiPHLE
        jSz/pD1Za5nQZ08BdwWwoaw=
        -----END PRIVATE KEY-----
      publicKey: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAncNGXzQtbSxiFh0vfykZ
        FjNGg9mG9dz4uTU8nPw963SZAglVcsz3N8XoYHv3KZrxYOf40UTAb/i8g9EVHZH9
        IviD5BXpR7kUSe6JZzhRxIHvxfJnVFv9nLcYFKhZATIus4ES0r2GhttHZvUWkz0D
        67ScsNHpL0tmWPEyerjg+17Q5UEeJ3novtCs9dU434kb9Qo0f5ffIUpy4Q5BXtV8
        uJiRMggo0PH1AwGoEvaU8659MXqDZF3BvtadglKcevcelT6JwZYQkjBu1U+qFjaE
        7kLd5qg1H8/DRuJ6HIfyybIdhGWTiU1HlsXGVsytM7lgurgOWmJJpt5nE1MrNgH8
        xwIDAQAB
        -----END PUBLIC KEY-----
