lsdmesp:
  ldap:
    readOnlyUser:
      password: x>ymCfFY:G06
    admin_password: FCf:ym>Y06xG
    config_password: FY0C6xG:>fmy
  confluent:
    connect:
      password: :Cfy0Gx6mFY>
    controlcenter:
      password: 6>mxY:0GyfFC
    kafka:
      password: 0Yy6:fGCmFx>
    kafkarestclass:
      password: F6xYGfC>y0:m
    kafkarestproxy:
      password: 6mxfG0YFC:y>
    ksqldb:
      password: 'y06xFC>mGfY:'
    schemaregistry:
      password: fF>G0y6m:xCY
  tls:
    ca:
      cert: |
        -----BEGIN CERTIFICATE-----
        MIIDtTCCAp2gAwIBAgIUHOF9TWHGS5U7h0vOaYpHvQJBLyUwDQYJKoZIhvcNAQEL
        BQAwajELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRUwEwYDVQQHDAxNb3VudGFp
        blZpZXcxEjAQBgNVBAoMCUNvbmZsdWVudDERMA8GA1UECwwIT3BlcmF0b3IxEDAO
        BgNVBAMMB0xvY2FsQ0EwHhcNMjQwNDE5MDgzMjA4WhcNMzQwNDE3MDgzMjA4WjBq
        MQswCQYDVQQGEwJVUzELMAkGA1UECAwCQ0ExFTATBgNVBAcMDE1vdW50YWluVmll
        dzESMBAGA1UECgwJQ29uZmx1ZW50MREwDwYDVQQLDAhPcGVyYXRvcjEQMA4GA1UE
        AwwHTG9jYWxDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALIItnHm
        fddl7rT/a8y3tFBINyAgMG/C1G6nRdnL+aLQRPaORtIifHA4n8/YVkPPT2gfFAnO
        Kf2bYYRvheFgECY0YSBA5gZOuboLMTwLFKS/Tcn1LcvSjr0wn3lh5trmrSY2tZtR
        +qski3LISmJh5YbIggocyN3ljNaVx+FbURPKs4DBmrAeSd2S40pIqUpygfa5+wzp
        9ePbasDUwQXIso4e6zfbMRzvW9fMQqDYpeQxb8uRV9PshD9QT76iI8MwngCqyOoE
        +ruxALaqYmMFBquisU8giDF9r/U3UCQNo8GHeJN9I3B35AMU1NkxU0lOHb9N17+s
        wMuVbHng/dFzjzsCAwEAAaNTMFEwHQYDVR0OBBYEFLRO2dWNxEZAflm9c4fJRSzs
        cmRxMB8GA1UdIwQYMBaAFLRO2dWNxEZAflm9c4fJRSzscmRxMA8GA1UdEwEB/wQF
        MAMBAf8wDQYJKoZIhvcNAQELBQADggEBACrZJqk+XMrj38bjkmumwM2kh5wd2r9e
        ef7DkERc77ueOjTs86zftgWqJOPYotaFbSmalbRY7/c2WAGqVYJSS/oyYuW/Bcsq
        LPbFFVQmYpL3f70AR95NRe5tLmHlMJnMafnZhtZJVQa4/ez09Ln6xoJcbou81g53
        sXLherkjZI8Pzij8SIq35UHXTj//djVgAXGlwikAkGjArctQWFUlAdQq+g1KHEWN
        xc4n2z4rr0gl2I6UMMgkzPPFLwLuGHFoworYovfclS7ZC8psawQTdvl53eb9b37I
        adw2s8qV8IeHd1FUaUw3wfR//tCAimS2LKW22IO8zu5imjDqk1d5Fdg=
        -----END CERTIFICATE-----
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCyCLZx5n3XZe60
        /2vMt7RQSDcgIDBvwtRup0XZy/mi0ET2jkbSInxwOJ/P2FZDz09oHxQJzin9m2GE
        b4XhYBAmNGEgQOYGTrm6CzE8CxSkv03J9S3L0o69MJ95Yeba5q0mNrWbUfqrJIty
        yEpiYeWGyIIKHMjd5YzWlcfhW1ETyrOAwZqwHkndkuNKSKlKcoH2ufsM6fXj22rA
        1MEFyLKOHus32zEc71vXzEKg2KXkMW/LkVfT7IQ/UE++oiPDMJ4AqsjqBPq7sQC2
        qmJjBQarorFPIIgxfa/1N1AkDaPBh3iTfSNwd+QDFNTZMVNJTh2/Tde/rMDLlWx5
        4P3Rc487AgMBAAECggEAM7alLDOb9R/WNTwGN5pa5YD8hjfjaetJYnTzLL77ncfq
        aEXOm4ZJ6B0CitCXyi2jLqbsXqbEeraSHnJ4jI0nU7meRsyjJEzk1P4gSIUdc3dg
        JJwzt8NLE/hWMl92O7qKrBFzMhEfg2vjl61HMgmmrr56S26uCAqAHOq3+yVXySv4
        rnnCMD71LUeY/+rRQL6Mrj+ZcheJMTV/oTh4N2LXPnt8D1zno8PmYJoCn2dx3UKb
        mtGLktx9Z5a5JFNWniby333GW2bpl+9nB8RsSVbxFY0+mQ7ZDDdYNL/fNwKuaDcl
        jboQQenl0fiZh+klZtnmmVCHAIq10H3KUdQ8hpd+tQKBgQC/P+NAvlCSqud1O3QT
        EpwncMZmbiXy56YeEISYg6ExdrsrvZZNLCKbbErYGuLHTw2ombb+fmW8uIsIUVGe
        e8dCP+KWGSyUmuKAR8+W1Qtp2TAqnAGCx+oj6jTuSBx2eatRZwgOEAGZwGy2o0qT
        5zCqZVVnHdZZnlCtlBIS//11FwKBgQDuT2ZXLJoyrELsRAvH/N8D2Qx4S+MGenQ8
        2B4PIl8JEKEHfHYpzMd6aRD2UJk0FMzyeI2QLPlAKoKKe+tOXxsUALs1vQNIwNzu
        g8zh8s3QX94FASqgDhsD14emo8dO3/RV2lRrPCMot2szADOjYM54140waTnWn4iU
        RetXW62VfQKBgQChQ9/+kfwjEJWHlxBznLer0j6Z1LuPLaI3q7oDWMstiG6fnYgF
        nve3kwMxYspjQdfEmYli43YqQnqKEvf96WXGCVSpOKUM0eW4QdVb3F15bbhd1Zq4
        ipZ2nmDvpELL7CB3zadPJFQVL9r7zoluWf4BUN1IzDIY85QYKclr2AwDFQKBgH87
        qRo12AXh7sER+3BE1BTL11qKuaUFz/WENVhDM5Y1aKQEkVnz2TTDz6iSk5k42ctD
        DeHCATl++L9TNehb4qslUM56IbzAK7S0bbjc14G/DVyCqO1XWpkMg4I2wvybmWoU
        7SlrrCHa+8L5Apjh4JqoCtuj8ptiBZuUUPgNHHpJAoGAPbObQNI4FPDWyxQJcgnE
        2rrJss9V8V9+Wp1ryr0LWGHAu/fFarWgbd+MLlwxPv6gLASD8m6A01rXgGxhG7qD
        aBAeNu+g4LnQ401YHC0FJMFj2aLB71sItsDHvI0njP76bhYTQlDd7wKetV29Ng/z
        4GnfO6iuq4qSSLRFQQNmJRA=
        -----END PRIVATE KEY-----
    mds:
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDUKi25vYRd37GD
        VTKuuREo+uOr8M3DtJ+Q/CDAlHIAuON9tOFCVQidHIeirrAb0CCtV6EohVCricsj
        J1a8vdF+IMkJqo1P3qdY4fal7x6+MSNhI+lPuF4x3gsyCr9SDovzuSoLpV/eeBBF
        f4qxTpWlPLvqhe1UNiFvTKR36YzfrU5wMDI7iIa6KeCgZv2AGHIyhBqRi/+NITzh
        bvQwovx6bPtPd6s66f+uJUv4/RxyitliDAH3TgnmYLDu4disfc7wop2JcJ1jvHkO
        k6HSslETfVYRWOjy3FsQf0k6I6pcIBphKr+nddcCwWl2BBTOdEC3Bq+yjd5fJxZH
        vKrAjGa3AgMBAAECggEAGOI7i7HhIPt3/+3RrHFzREmsw0FSeNYp8uDHXJ7sgg4t
        TFSXKOb9RCQQ+nEfoZt3Aa2p7q04KW5XX2+hOjDPLcpdmd8hhNEZ8pBKE+soQWlU
        +3MxTZLTpWikCoH9L3waSQMaHdSPGnIdgnEzjJkpbwBhD+AWVk6k/D9SeOfxCFi9
        5G/8ie0nmkt3Nkvbc5oQRpRRDZg3L30ESdszcgRBurgp6e7iwUANHBnG9gvNWYJv
        DEqQWhfqFlQAsX3Qfbdm3BtXOuOo6ysk2GbsQVbwPdDn2uXbJuiiHsiN84ArEvm4
        +cq87ZsZx/fKIbPpEsO6VSxbjPO8lIUG8lqTuZE4yQKBgQDWpjBHawsZHF9mf9kq
        p9EOXIfG0V48q9puViQAV7OJjsFOaCWCOhYmR6xXOUc/ZVZkcWf0rn6A0vlm4HN6
        dpR6B/0sMw6lRdkOi4kNyMghbB6oCcOcTjAzGFkrwOFYjNWd3DCBvP5P5DFjgPo7
        Wu8V0BVwb8g8N2doz8BLqqJs2QKBgQD9CXd3g9CoIpwMqTxq5p3BGiiAhAmQ3ZKu
        8RceoyQL00c0vEOZfKEUh0xoikN2ulDMLOLYDrv6tHKP9s0FlaaRqDX1jRtRmMP+
        AI86OQB271qgpcJLAKKYugdqqBDCT0oWnzK8mOKOwrim+J4MUawQk+PARk83RUDn
        Fy8CYDx2DwKBgQDC/2zipJMLd+QPCNwvzQ61XkgWzUMwGOsxy12fVg0LTT29Tg2t
        NbnDgt9Eygs4w4Xtb70B4reXrpHV7Nfbi/gsuC8+RQ/sAv1CIm8ar6ln+4IKI/yp
        dbqB4H+5qNrPB/pUE6GZaykZSPO5MoWhAGYsycGASHx+f9KYvAs0ckpmWQKBgEtN
        9e/rmr1vD2H1O7XUzD4butIEeZRTXMQTm/3SL3gVeKuJG9Uh8g5Z9bNm8ozzBfi9
        owUJ3YfPDAksOfffgaL3nJdnVyoBfNKq9/Ur4aeDtET7D8eieMFbG7nyKoqpbjMt
        TbwzA7nY2XtXojGoXLzSRoWCZzDbu2UK0UKzwUqhAoGBAIdmetF7OliIEuRwMa5u
        qFIoanLn2ByiWUmd7yiGtCOsjoSgwVPh5G0nlEeTEw45WJYl61Yc1iSdMeJ2ZOlm
        JvaBucQyjMG8baZdHlsDPA7Uu2Ug+HTB47kdFQt7Jqu0ZQVadPhSO9vK9bKz8h1n
        jaiNRBSLUZO1uyxy9RdpXB9s
        -----END PRIVATE KEY-----
      publicKey: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1Cotub2EXd+xg1UyrrkR
        KPrjq/DNw7SfkPwgwJRyALjjfbThQlUInRyHoq6wG9AgrVehKIVQq4nLIydWvL3R
        fiDJCaqNT96nWOH2pe8evjEjYSPpT7heMd4LMgq/Ug6L87kqC6Vf3ngQRX+KsU6V
        pTy76oXtVDYhb0ykd+mM361OcDAyO4iGuingoGb9gBhyMoQakYv/jSE84W70MKL8
        emz7T3erOun/riVL+P0ccorZYgwB904J5mCw7uHYrH3O8KKdiXCdY7x5DpOh0rJR
        E31WEVjo8txbEH9JOiOqXCAaYSq/p3XXAsFpdgQUznRAtwavso3eXycWR7yqwIxm
        twIDAQAB
        -----END PUBLIC KEY-----
