lsdmesp:
  ldap:
    readOnlyUser:
      password: Sql6yuRELFabG50
  confluent:
    connect:
      password: abLSuqF0lR5yGE6
    controlcenter:
      password: qlGEyR6F5uS0baL
    kafka:
      password: SRuE5LGlaq6Fb0y
    kafkarestclass:
      password: bFlRu5Eya6L0GqS
    kafkarestproxy:
      password: lGqaSbR5u6L0FyE
    ksqldb:
      password: GaubRFEqyL6l5S0
    schemaregistry:
      password: FS0bEyu6LlG5aqR
  tls:
    ca:
      cert: |
        -----BEGIN CERTIFICATE-----
        MIIDtTCCAp2gAwIBAgIUdgOn7H53BrBPDfsKu87SxdphiHowDQYJKoZIhvcNAQEL
        BQAwajELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRUwEwYDVQQHDAxNb3VudGFp
        blZpZXcxEjAQBgNVBAoMCUNvbmZsdWVudDERMA8GA1UECwwIT3BlcmF0b3IxEDAO
        BgNVBAMMB0xvY2FsQ0EwHhcNMjQwODAyMTIwMjA1WhcNMzQwNzMxMTIwMjA1WjBq
        MQswCQYDVQQGEwJVUzELMAkGA1UECAwCQ0ExFTATBgNVBAcMDE1vdW50YWluVmll
        dzESMBAGA1UECgwJQ29uZmx1ZW50MREwDwYDVQQLDAhPcGVyYXRvcjEQMA4GA1UE
        AwwHTG9jYWxDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOS/DSZj
        92Ma31V22rKH/OrN+fOG8m5kQj/mzb3lWlkBROCKiXdKwT2EgmuMcpC8stYf5uQ/
        zjEGj8+7Aeaj6Izz5NbfVgryB+OXJUuXO/skLmS8gn/hLjw2SBjAyaummJfTK0PH
        5YiTdD6mtxERbHsZ3KwmshuAmMZPe6mjxSDbl6dokI0i1gI0nLu7QCORpOy4y8uf
        o+QpD5iYmzVegpq2NGNwTjdttMf8jHoZmyzNWbWvHYFKXou4Mn9ICWkGMitEBznx
        sTjAd/k0qm/q8ePUnaSxJlEse/kulF2SAaiS35Mf2st/Q5ufh+kK8WXJcHZKQGiS
        DinU27Ubn+rb7WcCAwEAAaNTMFEwHQYDVR0OBBYEFOCJdrlTrbJyHy0e+2QQ1XKA
        weWnMB8GA1UdIwQYMBaAFOCJdrlTrbJyHy0e+2QQ1XKAweWnMA8GA1UdEwEB/wQF
        MAMBAf8wDQYJKoZIhvcNAQELBQADggEBABNJ9UtgxPhQ3ns307kJZS+XoHmHPmzb
        lT+1tylrJV4jP67uQQpv9cSkNMpn3o1/FG9ISjTAgrU3VCaKKEwY/2PrYyCnvxjk
        egihsvgrjN90XtguL9QUB39mUP7UlK4xqilBk002F7oIiqV0Q135e1ped4Wj2fAC
        OrFpsv6fFlk8EprbY9EZOHETowYT2G+HrBdkmwzRzS7hwXLfBgpG+89N29x4FEHp
        Vz//fCtPjxbS2soki3+UxyxDKwaWvIpfqi3WaAzLlTn+fgPR6GSkFPXWLdat051t
        1Ufg2GasYf0HaPikVdt5A6vpV3Cf9vf6WF1lyaTndS3EmOeLEVhjBV0=
        -----END CERTIFICATE-----
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQDkvw0mY/djGt9V
        dtqyh/zqzfnzhvJuZEI/5s295VpZAUTgiol3SsE9hIJrjHKQvLLWH+bkP84xBo/P
        uwHmo+iM8+TW31YK8gfjlyVLlzv7JC5kvIJ/4S48NkgYwMmrppiX0ytDx+WIk3Q+
        prcREWx7GdysJrIbgJjGT3upo8Ug25enaJCNItYCNJy7u0AjkaTsuMvLn6PkKQ+Y
        mJs1XoKatjRjcE43bbTH/Ix6GZsszVm1rx2BSl6LuDJ/SAlpBjIrRAc58bE4wHf5
        NKpv6vHj1J2ksSZRLHv5LpRdkgGokt+TH9rLf0Obn4fpCvFlyXB2SkBokg4p1Nu1
        G5/q2+1nAgMBAAECgf9OYdO8KUw4ftIk9vjAwp+ER9eJGzS+gpxp12WouqeB9KZB
        2TbsRhTxYxMUx1KzftkeaeyJu8Uy6v546P9aM5dRmOv8Cm8N31Ni8HYeRjRVr6yn
        2CmKNpDoZlv4yhb7j+/ywSJZQjRWwxPLDsdW5z391EJmEGqiOtIe6Tn2vIsXGizB
        kegoIwwh/3KrUPwf6umQXwvTxewkNlWV1cuwOQu8ES6qNlC9oOm1r9XVnQy7T6pF
        XGe1KUftZJzrbBK4Gse3w4q5Z1DRHXbkMkumoqX16msnAwwB4vMx3jkTcy1rW5n5
        ac3TqyrrSA2GnLHB1fLoshxdv/Lg8tCqLilJX30CgYEA+nr8u5zhCpxsd7Z1RuC0
        xy/ialcqzwr674vIAzNYTlOU2UatxdW5LfNwC76HYzP1nwISTxLDrg8FMMCLNKeh
        bwQycT1rhAAx6rqpUNMVt0rb24hd2JLqyEI228Er4665fQyoLXKbnI0/E3HLBLwu
        Ef7HQsZ6PbEqlFrJgxrPDFsCgYEA6cl1FXPG9EcB82iI+CLiRTqhsSEAV+9SrLgt
        B6U7q+PnEfbOQ3Pda72PSjIS9kaVZVhCJkRXYZi53FqaKCnFjgGmolfMlfX2TavV
        3q2739mi29o3zxCmWIYMtqql547nbeC6y+/pBNWeTsQaepTtxvlHRRzoCkzdwZdL
        Uw9XoOUCgYEA38a8wAhZ7RbuuMzjXZ0nJMUc7JBPiIVwxk4FNQbMH74AP1UrrpFQ
        TUMtmPBxGCm1iIdbQBWtiHWW14VNWI9iZEJFpnGO+nEKJ4D3/2N2BTj1zt23qeMn
        qh2t0Qp1YYYZ5SRHo8K+T1DJR1/kVqigKCeMcZXMZA1B0ySA34Y17/0CgYB0O1O5
        yakFs/P1V2iZrYY/kwnmrZilH3hEJQFGRtEnAZTVapZcFNPmCAWghsrEpI0MKNgi
        fGHRRQRK2MTB6RquIoX9Opediv7c2Ozo3AmHHoYItjJ/ATEi2+qgOrFnMbY/+7YD
        RJDedXJSiM79WOPqw+66HsgCrvqlkBnD/uG7PQKBgFQ89NE5Zkcv/8V55nwIQybq
        sqYp6zp2pFkcIbWTJ6lPkYLssuwDAgGuJgEX/3Fgam8GPcRzyqarP13j06l/50t5
        KPvjjGApR5qUKehOPSPs2dlBkSFA0IwfMdEE+rSED/Hf/cnVvXp4VHjFwWxw1PJC
        Nxkci+v6LEtQexNAh6CB
        -----END PRIVATE KEY-----
    mds:
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDnCk5rOA5PycAP
        SmPoRsb0ueJldUFNFFkKrKHEHBZkunMY+CgjYrljMH5RgxfXxG1bduG8Q574ES8B
        hcYHckz8XTWzSzeLvvAM/js/PZ9/jLctBiBQa012o+hLrdbjx3wOBqMt2JQenZFU
        ymG7p6hmA9M9xxgCyg3EkaKO4TUA2Vd6RXicpJOgG6Z+Q6JXsFr8XDihVWNc/1RP
        ch/unVndih30LQ75m0gjljpM+SJVuPgyKGGa2USBdGWspS5RXnORzL7QBjQAWmqT
        B1Bz0NK9qx2MsPlz6VLVDr72ChpvNPg1Lcb2mKs/dVMi4Nj+bjAROmIU39bmtNNU
        ud6dv8qRAgMBAAECggEAEdcJZB0Reda9xlB7s3FXpoj98tChiLakA39+BDsY/ZEq
        Fwj+bHEQmJijgF7LhgUsXo4o8xUTntsQ0qDGQEfyqt/1qBEMSnWlapNs9r6m5L30
        XP0mnJ8Ufa89Xi6fs7nxGdIoYn9hPJX1JWN1NXzGM45jDtejQn/gnUeTkk3Qfm6k
        Uk+SHvHcWFBEg8yd0/x+cA6LyWPWuLC8n3iS2NXAhlG+y27fOPEJmlsZ0cEOZpFk
        2ho04ZiLvqiM1YhiLlTcKWJGGZKF95fZyfImpzd97UfAuqabSMiJcSsfMjsJL15f
        VhPVfbB9ds4RBguTP9DopTCZ4uAysYTsEtifPXDmIwKBgQD39/WdVSieGFEZjWbM
        LfAOm2Px5LGHM8QvydRrNTK5b0LLK49JYRIAFpOxrjBiciQi2Wd/uF717p+9Ajhu
        PHKE0HjO8So3XP2Bn0joNt2dCnEX2oyr9RNsH9JLQPK4keFryD+4qETcK4NNm05e
        awylYAFA+gBdmmL9F6CqVKMH/wKBgQDuhfwpkC4QfCZ6OE+3GNAv0cGfv98RRuCs
        +OVY/N7Vi2DW1ZVqv9rtlGxhRSyNOAxZ8A8RF9oG+zqrcaD/LeJ5Gci4TrpreGXR
        xJLYkz7hyUyWaEqzw7HYjumfBKEJQ8OQpvIS+/IqoIcP63P1nGcostRaucpgCzUM
        M85BAVitbwKBgQCd0cwaEawjSti7CZsGkqo5sb6fou02XsUboTo37YjWKrD5PEUa
        79QUCEqCCJo03e6P24ya5k5R+kjic/pUdtZwH3r0Qtualu2lxSoS2XCc1Zt7Ehb8
        DqQI6gve53xT6kztW2rq7PW+p1cPWqw7PaizzHGf2D3JVUxxRstz/SAyIwKBgGaH
        a5RGKLbnVvbUe9edr+fOR2eu52kayXsw5g0xbWvnpLHUT4z6eVYEpe3N+U+e1xhV
        63QSh6LWnSqTBnyKMb6SichH9zQ5JbNcxy6XZMFTcTt6CxpotWr8S4oSSFKeMVNd
        n9LvP/J43HXIZSkfmOxSqptxH3/XcW8UWcVxmbe7AoGAR2DOiNF4giAtRJMCYxq2
        JVcovnCa9K/P6ersotFQ3gT5/9lFN1EYevjcDa7SIq6OXDPihJwSF8NEXUOVDvVT
        74FuutvDDlLmBow4yxrCVpISWN8B56oprBWTp2Z0YxoqyWtiGrsi44z3vN/PEvBp
        b34OvDxPU9rilC0rDq0i+rQ=
        -----END PRIVATE KEY-----
      publicKey: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5wpOazgOT8nAD0pj6EbG
        9LniZXVBTRRZCqyhxBwWZLpzGPgoI2K5YzB+UYMX18RtW3bhvEOe+BEvAYXGB3JM
        /F01s0s3i77wDP47Pz2ff4y3LQYgUGtNdqPoS63W48d8DgajLdiUHp2RVMphu6eo
        ZgPTPccYAsoNxJGijuE1ANlXekV4nKSToBumfkOiV7Ba/Fw4oVVjXP9UT3If7p1Z
        3Yod9C0O+ZtII5Y6TPkiVbj4MihhmtlEgXRlrKUuUV5zkcy+0AY0AFpqkwdQc9DS
        vasdjLD5c+lS1Q6+9goabzT4NS3G9pirP3VTIuDY/m4wETpiFN/W5rTTVLnenb/K
        kQIDAQAB
        -----END PUBLIC KEY-----
