confluent-for-kubernetes:
  image:
    registry: localhost:5001
  namespaceList: ["lsdmesp", "fun"]
flink-kubernetes-operator:
  watchNamespaces: []
lsdmesp:
  cpRegistry: localhost:5001
  armyKnife:
    registry: localhost:5001
  monitoring:
    kafkaLagExporter:
      registry: localhost:5001
  ldap:
    registry: localhost:5001
    readOnlyUser:
      password: Developer!
    admin_password: "confluentrox"
    config_password: "confluentconfigrox"
  confluent:
    connect:
      build: false
      image: lsdtrip/cp-server-connect
      password: bk(2KW{LgFj3
    controlcenter:
      password: '{(kLWbjg2K3F'
    kafka:
      password: (2FbgWk3Kj{L
    kafkarestproxy:
      password: WkF{L(bj2K3g
    ksqldb:
      password: (3WKbLg{F2jk
    schemaregistry:
      password: jgkW{b23KFL(
  tls:
    ca:
      cert: |
        -----BEGIN CERTIFICATE-----
        MIIDtTCCAp2gAwIBAgIUR4rqxCFOf/dWByM/bkS+6Ml3Jb8wDQYJKoZIhvcNAQEL
        BQAwajELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRUwEwYDVQQHDAxNb3VudGFp
        blZpZXcxEjAQBgNVBAoMCUNvbmZsdWVudDERMA8GA1UECwwIT3BlcmF0b3IxEDAO
        BgNVBAMMB0xvY2FsQ0EwHhcNMjQwNDE3MDM1NDI5WhcNMzQwNDE1MDM1NDI5WjBq
        MQswCQYDVQQGEwJVUzELMAkGA1UECAwCQ0ExFTATBgNVBAcMDE1vdW50YWluVmll
        dzESMBAGA1UECgwJQ29uZmx1ZW50MREwDwYDVQQLDAhPcGVyYXRvcjEQMA4GA1UE
        AwwHTG9jYWxDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANLxzDJw
        ym6RnMXladXi/LOFlKrAutK9GCWweXGp1C1Ks3LWQbon5SQb+sw7mvTA/JQE1Iic
        h5r0Y05VKE9aE/r4G4eBJ+ZLaHFocdG4ASFd35Ce09OMO1vZD7hwVjYkeQir+Ntd
        YAL+W+Mr2z1PdEsNq1+Ip/1XFcNe5Cce87MdEh/GarQiiPUxn1rFvxXMDLHP9+Q+
        6Ort5WhETb+xbErYQhkoJPgkS3GvZ3muMlfUj1BTztDyFIxK9DEOEtAl1fZ0LXsJ
        orCOVLneptdzogebQHhPbCvrEFt4VilLxrMlaqMvh4UqwuQtrkwmMXK4yXIF6eD+
        2tv72VpKBsGRY6UCAwEAAaNTMFEwHQYDVR0OBBYEFLtW2Oo/YvKKBMUNCIZwyMvi
        cfEoMB8GA1UdIwQYMBaAFLtW2Oo/YvKKBMUNCIZwyMvicfEoMA8GA1UdEwEB/wQF
        MAMBAf8wDQYJKoZIhvcNAQELBQADggEBAMdDxfrLq9BkEqZgIJ+1CKK6Ubpp2ChW
        189E2HbFO0OjCA+7BRLUME1K0GP+uE0txfil1xG8cOusfyE82NaS9ENHzJTq1xga
        UGhLf49/19rLDRGsD6TcelvkOW3sT2430bwQi+G4dH9gUv8tg/2ZpQDqYJSc4rWG
        PXnKzZtx7OzcykBSHODJKh0mbAJw2TZPdDFmxbU2/8FeDSIHD/C1dFQV6D/vox+/
        51ESv2cyA8ltg8N7R7DHsyBerHT6gLNJfbpOwJ0m6KLYfl60smBza5j/mQyx/WXN
        79mOWZfG8ISi/+MG2FuULN5G+ROSx1UZ3F5gBOOhOPPo668sklFDVVE=
        -----END CERTIFICATE-----
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDS8cwycMpukZzF
        5WnV4vyzhZSqwLrSvRglsHlxqdQtSrNy1kG6J+UkG/rMO5r0wPyUBNSInIea9GNO
        VShPWhP6+BuHgSfmS2hxaHHRuAEhXd+QntPTjDtb2Q+4cFY2JHkIq/jbXWAC/lvj
        K9s9T3RLDatfiKf9VxXDXuQnHvOzHRIfxmq0Ioj1MZ9axb8VzAyxz/fkPujq7eVo
        RE2/sWxK2EIZKCT4JEtxr2d5rjJX1I9QU87Q8hSMSvQxDhLQJdX2dC17CaKwjlS5
        3qbXc6IHm0B4T2wr6xBbeFYpS8azJWqjL4eFKsLkLa5MJjFyuMlyBeng/trb+9la
        SgbBkWOlAgMBAAECggEAYO008Cpugc7LtAz9jAegKNck4C7tyT6VFWBY9TbdZTBR
        c19q1SBWxDhNDcIHqhXxGQx9IgaWssc/yDMN8iRIUQXnFGTu0f1tUMr2nbBIaK4L
        N5cbazWg4svC0vNfUcKBkNAAab+micmZrDEvLKVRINl3mM6griJxQBPejvFEdlR7
        TX9+7AblK6cI9SZeTBrc3m3ijYNarAMmAZHl9BjatB3UwmFGi3Vugfz5QgmwAZrK
        slA/pjP83tRdWzv3PFVLWpElBKQFfEgCqIMj5Z8Lbo0FDR2QkO2tYkfPp8fQ7SFm
        x/d2vudXDmuB9t4DbAq4EtkDxLChNow1pv0BabGIgwKBgQD/Ir7izECcVChyyzt8
        sV6KsBhLvkBO++MducqY+dsrRXi0Cn2B6ORoSlE84q2hh9vgc4F1zvKfqqHeUi9i
        BGMl2DDbMNKUl/62t3/vg/eLhLjvKOe9/SUsTEBLM5EVFKGHD4pFxkRliRecKGRY
        uuqgIZi/G2KSylBuUtDYjW2PswKBgQDTqLqxmGgYvKmzY0Ad6OVZXDF6NYtBf0mJ
        FefdNoEr9aeAWgMa4sWJ7ANIUpXTGQg97HOYDYqSxwQM9eR/RioSx5xNbu1Rr6kt
        L49GjB/PwD70ObewCCIUQu4MlkqHEkBoTWk5V+p73Cv0L9Zqu87kOX5oDhv8p1RA
        /lQ6C0rTRwKBgQDs7ZtOildF1XFqiQjJFv2w1S76x8Z4krmqlSprPTwmxvD8YPGE
        fn39y2X9oJOVedDacuk6OeBeHdsL1k5iO6jHMCjOpFwp2ayUiXupNWfgjHQgxF/Q
        sxCePoFGVLDaXrpR7kB9400I7XKbdXcaXxobcpeigQ/dOTvP9+Ax+cRQuQKBgAII
        3zKR2n5SYfc9fwJKmNnRDxCzrxEEHjrZIQ95VKiNhfyv4NPDVk7LHAT39kS/OtsN
        iNbvWmOq0hkly/qFPCZOEOyVomZkn+W1TVVKR4wBtxk17NQeX+V99zfbwf+mZ0QZ
        ameIttJV/X4tb4w7HfQHsXVinVZCbYbqavjb3u5FAoGBAKfwbPlIdRSrPZUUaM3v
        wRBUuV76ciGfne8Y1p7z1DF7p+KFgK2EgWTBT8NS1YHdqGvyYMghH+tM0lbdTX96
        PBcIT2f9uAN+RXLa18xtAYhH72qDGV9bhatGreY/zcD1lw3QB1WJxUtEM20uYGbk
        +eGULfLfFxxtzetsFkFS8uTp
        -----END PRIVATE KEY-----
    mds:
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDD0UBtLnOrqcGl
        6+kqezgBNL2ZSMeHRsZI8+nxxlfrC4JdES6c7dncLkD+w9k3Rj7aMxKlKKwEr1jA
        LeWj3dLq1oE9jnc4lcPPHyEAcsIzmjXh7a0UyQgjcg06DvGZ6V07ZRvyQc9kBi+l
        2Dtisr9WgBhgzL6RAQGAhTfuUVMXSAlaiGDxaAbQzzz2U4jKIFG4issfX8stXbRN
        vyxIT4osYeH0iVnan2OIl4L/Ss8fjSWLm99baqzaMp33qwIozuvFGyUfjI2taqrM
        6lTBQ0RyCw6gPucR4B5+7mMqBt9vyP51PzF/cXGLrs+zpfokdd/7Bin0UQumBr3X
        BUoZNBChAgMBAAECggEADKQqGMJPxQHBAXFLjKqxZgvdv5MIuoLG/eJX3yay+fa0
        vvBYhi3+tgL7FCytja7IaPVfcJpsZyMGGOX9oLNgezjyKqNTWVZQcphrsifhF0wP
        IBuOubxJUmHPA8lU2d73CK9m0KAPVOw8pY63irrHtRGw692GjJLi4hqiOTg2eSwC
        vIpjHOERiSRnxW36eB/Pw+aU3Ea8lL6fI/1WJe8twZvSv0+sg7+x4fqzorxsBKVJ
        RjU6Zc/VD1KCmwk+1E1rLSXKZwWQejXkHndtk/BDqI/tuxvI12ckdpSNDIhB94E8
        I3LNCrygPzZSkhEnrguHNaaI81cwp+cvaj0IHq8zJwKBgQD8fe0btlpKlbYsCx1O
        qYWsrxZu51MjVTjhxNY77zgVSuZFML2Ir8ze15WIpmnL2uUoi8vLCmpYkVzU/FE6
        8wIkUaci9sXJqlzlhC8BrWXl2tRzLViJ6lJkjRY2ULQY/xsh7u3fz1Klv2mXBY79
        91CsmpbAqoZzPPxbovX0/vIFzwKBgQDGib5BSqde5PKrNuw2JdTE+4REpkeEwC4w
        HTJY3AgdxZ/GU2gw2HAYBK930yHaIO2JhQ/O6T8A2C9PsL44REv6iTpfEiNnW3bV
        TqYLCmUIdSwUy7Rq27zj9th4TC33UJuRtyQuOldPy9UiERZyGtGkx0OeDxRyH4hh
        +d1FPxaOjwKBgCcqiXtBACSNsKKIXtVy6m9tAXfWnkje0WIEHI9TfkmfQrT86Imp
        a4gtvN5jogmjPOTbOpOWXAS9F79aHGeehniHyftceDXeHWbk6D3EXggXt9jd8dwC
        4yEB2a43OpieCeFrpK6RBGr9lC1/CT1P/c2odTYRvaVmkmbMkoacfYJ1AoGAXgR+
        pzauGb77t96zb1Ts9DdTRJslhRTpCnnZDMFtyoN6jRWUYoUsWANoAKtn/X7YXeY4
        PTixUDoP9YHyIn0dKdBwZvMU9u4WUR8EfHf4rk+mh1aL4oqaYa3Uhus0XUi70v5S
        UN3p2OziylYjNffDTW/bcm8btIuALz1+7jrY+LsCgYEA5ZIX6rT1I7eWffNBUgEY
        aZ5qxnAAU8lVdwBkOucjlCOorzntxdGsxRqSYFHiPTqPDJJGMC9vo2gvNcWaWHd/
        MHokr2ro/F6MOnE1xFU+LkVYE0xiuX98/xUCwF+8rW03IRzvbFwRqy9VrMX/L/Va
        NzaC5VEeD7FxYJTHHO3ixYY=
        -----END PRIVATE KEY-----
      publicKey: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw9FAbS5zq6nBpevpKns4
        ATS9mUjHh0bGSPPp8cZX6wuCXREunO3Z3C5A/sPZN0Y+2jMSpSisBK9YwC3lo93S
        6taBPY53OJXDzx8hAHLCM5o14e2tFMkII3INOg7xmeldO2Ub8kHPZAYvpdg7YrK/
        VoAYYMy+kQEBgIU37lFTF0gJWohg8WgG0M889lOIyiBRuIrLH1/LLV20Tb8sSE+K
        LGHh9IlZ2p9jiJeC/0rPH40li5vfW2qs2jKd96sCKM7rxRslH4yNrWqqzOpUwUNE
        cgsOoD7nEeAefu5jKgbfb8j+dT8xf3Fxi67Ps6X6JHXf+wYp9FELpga91wVKGTQQ
        oQIDAQAB
        -----END PUBLIC KEY-----
