lsdmesp:
  clusterType: "kind"
  cpVersion: "7.6.0"
  cpOperatorVersion: "2.8.0"
  storageClass: standard
  defaultReplicationFactor: 3
  defaultMinInSyncReplicas: 2
  defaultNumPartitions: 6
  confluent:
    kraftcontroller:
      # if `true`, then will be provisioned
      enabled: true
      # size of the pv needed
      dataVolumeCapacity: 1Gi
      # pod resource limits and request
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 20m
          memory: 512Mi
      # number of pod replicas
      replicas: 3

    kafka:
      # if `true`, then will be provisioned
      enabled: true
      # size of the pv needed
      dataVolumeCapacity: 20Gi
      # pod resource limits and request
      resources:
        limits:
          cpu: 1
          memory: 8Gi
        requests:
          cpu: 50m
          memory: 3Gi
      # number of pod replicas
      replicas: 3

    kafkarestclass:
      # if `true`, then will be provisioned
      enabled: true

    schemaregistry:
      # if `true`, then will be provisioned
      enabled: true
      # pod resource limits and request
      resources:
        limits:
          cpu: 200m
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 512Mi
      # number of pod replicas
      replicas: 1

    connect:
      # if `true`, then will be provisioned
      enabled: true
      # pod resource limits and request
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 20m
          memory: 1Gi
      # number of pod replicas
      replicas: 1

    ksqldb:
      # if `true`, then will be provisioned
      enabled: true
      # size of the pv needed
      dataVolumeCapacity: 5Gi
      # pod resource limits and request
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 1Gi
      # number of pod replicas
      replicas: 1

    kafkarestproxy:
      # if `true`, then will be provisioned
      enabled: true
      # pod resource limits and request
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 512Mi
      # number of pod replicas
      replicas: 1

    controlcenter:
      # if `true`, then will be provisioned
      enabled: true
      # size of the pv needed
      dataVolumeCapacity: 10Gi
      # pod resource limits and request
      resources:
        limits:
          cpu: 2
          memory: 12Gi
        requests:
          cpu: 200m
          memory: 6Gi
      # number of pod replicas
      replicas: 1

confluent-for-kubernetes:
  name: confluent-operator
  licenseKey: ""
  license:
    secretRef: ""
    directoryPathInContainer: ""
  managedCerts:
    enabled: false
    caCertificate:
      secretRef: ""
      directoryPathInContainer: ""
    certDurationInDays: 60
    renewBeforeInDays: 30
    sans: ""
  imagePullSecretRef:  confluent-registry
  image:
    registry: docker.io
    repository: confluentinc/confluent-operator
    pullPolicy: IfNotPresent
    tag: "0.921.2"
  priorityClassName: ""
  replicas: 1
  namespaced: true
  namespaceList: []
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  terminationGracePeriodSeconds: 30
  debug: false
  affinity: {}
  tolerations: []
  podSecurity:
    enabled: true
    securityContext:
      fsGroup: 1001
      runAsUser: 1001
      runAsNonRoot: true
  containerSecurity:
    enabled: false
    securityContext: {}
  serviceAccount:
    create: true
    name: ""
  rbac: true
  clusterRole:
    openshift: false
  telemetry:
    enabled: false
    proxy:
      enabled: false
      credentialRequired: false
    secretRef: ""
    directoryPathInContainer: ""
  kRaftEnabled: true
  webhooks:
    enabled: false
    port: 8443
    tls:
      secretRef: ""
      directoryPathInContainer: ""
  pod:
    annotations:
      prometheus.io/path: "/metrics"
      prometheus.io/port: "7778"
      prometheus.io/scrape: "true"
    labels: {}
  licenseSecretRef: ""
  mountedVolumes:
    volumes: []
    volumeMounts: []
