FROM confluentinc/cp-server-connect:8.0.0
USER root
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-avro-converter:8.0.0
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:0.6.7
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.8.4
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-http:1.7.10
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-http-source:1.0.1
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:15.0.1
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-s3-source:2.6.16
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-s3:10.6.7
RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:3.1.2
RUN confluent-hub install --no-prompt debezium/debezium-connector-mysql:3.1.2
RUN confluent-hub install --no-prompt tabular/iceberg-kafka-connect:0.6.19
USER 1001
