FROM confluentinc/cp-kafka-connect:7.6.1 AS cp
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-avro-converter:7.6.1
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:0.6.0
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.6.0
RUN confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:1.8.1
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:14.0.3
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-s3:10.3.0
RUN confluent-hub install --no-prompt debezium/debezium-connector-sqlserver:1.9.7
RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:1.9.7
RUN confluent-hub install --no-prompt debezium/debezium-connector-mysql:1.9.7
RUN confluent-hub install --no-prompt debezium/debezium-connector-mongodb:1.9.7
