{
 "title": "Confluent Kafka Streams",
 "description": "Kafka Streams JMX Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "query_result(kafka_cruisecontrol_loadmonitor_valid_windows_value)"
   },
   {
    "name": "strimzi_cluster_name",
    "label": "Cluster Name",
    "query": "query_result(kafka_cruisecontrol_loadmonitor_valid_windows_value{namespace=\"$kubernetes_namespace\"})"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clients Running",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_streams_stream_metrics{state!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alive Stream Threads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_streams_stream_metrics{alive_stream_threads!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Stream Threads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_streams_stream_metrics{failed_stream_threads!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Records Processed per Second",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(kafka_streams_stream_processor_node_metrics_process_rate{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Dropped Records",
   "type": "stat",
   "description": "The total number of records dropped for all tasks.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(kafka_streams_stream_task_metrics_dropped_records_total{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg processing latency (ms)",
   "type": "stat",
   "description": "The average processing time in ms for the average of all threads and tasks",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " avg(kafka_streams_stream_thread_metrics_process_latency_avg{})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Kafka Streams Client State",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kafka_streams_stream_metrics{client_id!=\"\", state!=\"\", }",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Kafka Streams Alive/Failed Stream Threads",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kafka_streams_stream_metrics{alive_stream_threads != \"\", } ",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": " kafka_streams_stream_metrics{failed_stream_threads != \"\", }",
     "legendFormat": "{{a}}"
    }
   ]
  },
  { "title": "Thread Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Avg Commit Latency in ms",
   "type": "timeseries",
   "description": "The average execution time in ms, for the respective operation, across all running tasks of this thread.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg{}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Max Commit Latency in ms",
   "type": "timeseries",
   "description": "The average execution time in ms, for commit, across all running tasks of this thread.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Avg Poll Latency in ms",
   "type": "timeseries",
   "description": "The maximum execution time in ms, for polling, across all running tasks of this thread.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Max Poll Latency in ms",
   "type": "timeseries",
   "description": "The maximum execution time in ms, for polling, across all running tasks of this thread.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_max",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Avg Process Latency  in ms by Thread",
   "type": "timeseries",
   "description": "The maximum execution time in ms, for processing, across all running tasks of this thread.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_latency_avg",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Max Process Latency in ms",
   "type": "timeseries",
   "description": "The maximum execution time in ms, for processing, across all running tasks of this thread.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_latency_max",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Avg Poll Records",
   "type": "timeseries",
   "description": "The average number of records processed within an iteration.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_records_avg",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Max Poll Records",
   "type": "timeseries",
   "description": "The maximum number of records processed within an iteration.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_records_max",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Task Created Rate",
   "type": "timeseries",
   "description": "The average number of newly-created tasks per second.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_task_created_rate",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Task Created Total",
   "type": "timeseries",
   "description": "The total number of newly-created tasks.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_task_created_total",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Task Closed Rate",
   "type": "timeseries",
   "description": "The average number of tasks closed per second.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_task_closed_rate",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Task Closed Total",
   "type": "timeseries",
   "description": "The total number of tasks closed.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_task_closed_total",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  { "title": "Task Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Task Dropped Record Rate",
   "type": "timeseries",
   "description": "The actieve pro",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "(kafka_streams_stream_task_metrics_dropped_records_rate{})",
     "legendFormat": "{{task_id}} {{thread_id}}"
    }
   ]
  },
  {
   "title": "Task Dropped Record Total by Thread",
   "type": "timeseries",
   "description": "The total sum of records dropped within this task grouped by thread.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": " (kafka_streams_stream_task_metrics_dropped_records_total{})",
     "legendFormat": "{{task_id}} {{thread_id}}"
    }
   ]
  },
  {
   "title": "Active Process Ratio",
   "type": "timeseries",
   "description": "The average active process ratio by thread\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": " (kafka_streams_stream_task_metrics_active_process_ratio{})",
     "legendFormat": "{{task_id}} - {{thread_id}}"
    }
   ]
  },
  {
   "title": "Active Process Ratio by Task",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "kafka_streams_stream_task_metrics_active_process_ratio{}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Task Processing Latency Avg in ms",
   "type": "timeseries",
   "description": "The actieve pro",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "(kafka_streams_stream_task_metrics_process_latency_avg{}) / 1000000",
     "legendFormat": "{{task_id}} {{thread_id}}"
    }
   ]
  },
  { "title": "Processor Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Processed Records Rate per Second",
   "type": "timeseries",
   "description": "The average number of records processed per second by a source node\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "kafka_streams_stream_processor_node_metrics_process_rate{}",
     "legendFormat": "{{task_id}} {{thread_id}}"
    }
   ]
  },
  {
   "title": "Total Records Processed",
   "type": "timeseries",
   "description": "The total records processed by a source node ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "(kafka_streams_stream_processor_node_metrics_process_total{})",
     "legendFormat": "{{task_id}} {{thread_id}}"
    }
   ]
  }
 ]
}