apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-teamblue-admin-transaction
  namespace: lsdmesp-confluent
spec:
  principal:
    name: TeamBlueAdmin
    type: group
  resourcePatterns:
    - name: prod.teamblue.
      patternType: PREFIXED
      resourceType: TransactionalId
  role: ResourceOwner
