apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-teamblue-read-group
  namespace: lsdmesp-confluent
spec:
  principal:
    name: TeamBlueRead
    type: group
  resourcePatterns:
    - name: prod.teamblue.
      patternType: PREFIXED
      resourceType: Group
  role: DeveloperRead
