{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta2
{{- end }}
kind: Deployment
metadata:
  name: {{ template "cp-kafka-rest.fullname" . }}
  labels:
    app: {{ template "cp-kafka-rest.name" . }}
    chart: {{ template "cp-kafka-rest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cp-kafka-rest.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cp-kafka-rest.name" . }}
        release: {{ .Release.Name }}
      {{- if or .Values.podAnnotations .Values.prometheus.jmx.enabled }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- if .Values.prometheus.jmx.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.prometheus.jmx.port | quote }}
      {{- end }}
      {{- end }}
    spec:
      containers:
        {{- if .Values.prometheus.jmx.enabled }}
        - name: prometheus-jmx-exporter
          image: "{{ .Values.prometheus.jmx.image }}:{{ .Values.prometheus.jmx.imageTag }}"
          imagePullPolicy: "{{ .Values.prometheus.jmx.imagePullPolicy }}"
          command:
          - java
          - -XX:+UnlockExperimentalVMOptions
          - -XX:+UseCGroupMemoryLimitForHeap
          - -XX:MaxRAMFraction=1
          - -XshowSettings:vm
          - -jar
          - jmx_prometheus_httpserver.jar
          - {{ .Values.prometheus.jmx.port | quote }}
          - /etc/jmx-kafka-rest/jmx-kafka-rest-prometheus.yml
          ports:
          - containerPort: {{ .Values.prometheus.jmx.port }}
          resources:
{{ toYaml .Values.prometheus.jmx.resources | indent 12 }}
          volumeMounts:
          - name: jmx-config
            mountPath: /etc/jmx-kafka-rest
        {{- end }}
        - name: {{ template "cp-kafka-rest.name" . }}-server
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - name: rest-proxy
              containerPort: {{ .Values.servicePort}}
              protocol: TCP
            {{- if .Values.prometheus.jmx.enabled }}
            - containerPort: {{ .Values.jmx.port }}
              name: jmx
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          {{- if .Values.restSecurity.basic.enabled }}
            - name: lsdmesp-jaas-config
              mountPath: /opt/kafka/jaas-config
            - name: lsdmesp-passwords
              mountPath: /opt/kafka/lsdmesp-passwords
          {{- end }}
          {{- if eq .Values.internalSecurity.authentication "mtls" }}
            - name: lsdmesp
              mountPath: /opt/kafka/certs-lsdmesp
          {{- end }}
          {{- if or (eq .Values.internalSecurity.authentication "mtls") (.Values.restSecurity.tls.enabled) }}
            - name: lsdmesp-cluster-ca-cert
              mountPath: /opt/kafka/certs-cluster-ca
          {{- end }}
          env:
          - name: KAFKA_REST_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_REST_BOOTSTRAP_SERVERS
            value: {{ template "cp-kafka-rest.kafka.bootstrapServers" . }}
          - name: KAFKA_REST_SCHEMA_REGISTRY_URL
            value: {{ template "cp-kafka-rest.cp-schema-registry.service-name" . }}
          {{- if .Values.restSecurity.basic.enabled }}
          - name: KAFKA_REST_SCHEMA_REGISTRY_BASIC_AUTH_CREDENTIALS_SOURCE
            value: "USER_INFO"
          - name: KAFKA_REST_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO
            value: "bob:bob-secret"
          - name: KAFKA_REST_AUTHENTICATION_METHOD
            value: "BASIC"
          - name: KAFKA_REST_AUTHENTICATION_ROLES
            value: "admin,developer"
          - name: KAFKA_REST_AUTHENTICATION_REALM
            value: "LSDMESPRealm"
          {{- end }}
          - name: KAFKAREST_HEAP_OPTS
            value: "{{ .Values.heapOptions }}"
          {{- if eq .Values.internalSecurity.authentication "mtls" }}
          - name: KAFKA_REST_CLIENT_SECURITY_PROTOCOL
            value: "SSL"
          - name: KAFKA_REST_CLIENT_SSL_TRUSTSTORE_LOCATION
            value: "/opt/kafka/certs-cluster-ca/ca.p12"
          - name: KAFKA_REST_CLIENT_SSL_TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmesp-cluster-ca-cert
                key: ca.password
          - name: KAFKA_REST_CLIENT_SSL_KEYSTORE_LOCATION
            value: "/opt/kafka/certs-lsdmesp/user.p12"
          - name: KAFKA_REST_CLIENT_SSL_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmesp
                key: user.password
          - name: KAFKA_REST_CLIENT_SSL_KEY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lsdmesp
                key: user.password
          {{- end }}
          {{- range $key, $value := .Values.configurationOverrides }}
          - name: {{ printf "KAFKA_REST_%s" $key | replace "." "_" | upper | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $value := .Values.customEnv }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.kafkaRestOpts }}
          - name: KAFKAREST_OPTS
            value: "{{ .Values.kafkaRestOpts }}"
          {{- end }}
          {{- if .Values.jmx.port }}
          - name: JMX_PORT
            value: "{{ .Values.jmx.port }}"
          {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.restSecurity.basic.enabled }}
      - name: lsdmesp-jaas-config
        configMap:
          name: lsdmesp-jaas-config
      - secret:
          defaultMode: 420
          secretName: lsdmesp-passwords
        name: lsdmesp-passwords
      {{- end }}
      {{- if eq .Values.internalSecurity.authentication "mtls" }}
      - name: lsdmesp
        secret:
          defaultMode: 292
          secretName: lsdmesp
      {{- end }}
      {{- if or (eq .Values.internalSecurity.authentication "mtls") (.Values.restSecurity.tls.enabled) }}
      - name: lsdmesp-cluster-ca-cert
        secret:
          defaultMode: 292
          secretName: lsdmesp-cluster-ca-cert
      {{- end }}
      {{- if .Values.prometheus.jmx.enabled }}
      - name: jmx-config
        configMap:
          name: {{ template "cp-kafka-rest.fullname" . }}-jmx-configmap
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
