{{- if and .Values.prometheus.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cp-kafka-rest.fullname" . }}-jmx-configmap
  labels:
    app: {{ template "cp-kafka-rest.name" . }}
    chart: {{ template "cp-kafka-rest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  jmx-kafka-rest-prometheus.yml: |+
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: false
    ssl: false
    rules:
      # "kafka.rest:type=jetty-metrics"
      - pattern: "kafka.rest<type=jetty-metrics>([^:]+):"
        name: "kafka_rest_jetty_metrics_$1"
      # "kafka.rest:type=jersey-metrics"
      - pattern: "kafka.rest<type=jersey-metrics>([^:]+):"
        name: "kafka_rest_jersey_metrics_$1"
      # "kafka.rest:type=consumer-node-metrics,client-id=*,node-id=*,"
      # "kafka.rest:type=producer-node-metrics,client-id=*,node-id=*,"
      - pattern: "kafka.rest<type=(.+), client-id=(.+), node-id=node-(.+)><>(.+): (.+)"
        name: "kafka_rest_$1_$4"
        type: GAUGE
        cache: true
        labels:
          client_id: $2
          node_id: $3
      # "kafka.rest:type=consumer-metrics,client-id=*"
      # "kafka.rest:type=producer-metrics,client-id=*"
      - pattern: "kafka.rest<type=(.+), client-id=(.+)><>(.+): (.+)"
        name: "kafka_rest_$1_$3"
        type: GAUGE
        cache: true
        labels:
          client_id: $2
{{- end }}
