{{- $kafkarestproxy := .Values.lsdmesp.confluent.kafkarestproxy -}}
{{- if $kafkarestproxy.enabled -}}
{{- if .Values.lsdmesp.security.vault.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kafkarestproxy-login-vss
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.lsdmesp.security.vault.type }}
  mount: {{ .Values.lsdmesp.security.vault.mount }}
  path: {{ .Values.lsdmesp.security.vault.subPath }}/kafkarestproxy-login
  destination:
    name: kafkarestproxy-login
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Values.lsdmesp.security.vault.auth.name }}
{{- else -}}
apiVersion: v1
stringData:
  bearer.txt: |-
    username={{ $kafkarestproxy.username }}
    password={{ $kafkarestproxy.password }}
kind: Secret
metadata:
  name: kafkarestproxy-login
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
