{{- $controlcenter := .Values.lsdmesp.confluent.controlcenter -}}
{{- if $controlcenter.enabled -}}
{{- if .Values.lsdmesp.security.vault.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: controlcenter-login-vss
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.lsdmesp.security.vault.type }}
  mount: {{ .Values.lsdmesp.security.vault.mount }}
  path: {{ .Values.lsdmesp.security.vault.subPath }}/controlcenter-login
  destination:
    name: controlcenter-login
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Values.lsdmesp.security.vault.auth.name }}
{{- else -}}
apiVersion: v1
stringData:
  bearer.txt: |-
    username={{ $controlcenter.username }}
    password={{ $controlcenter.password }}
kind: Secret
metadata:
  name: controlcenter-login
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
