{{- $connect := .Values.lsdmesp.confluent.connect -}}
{{- if $connect.enabled -}}
{{- if .Values.lsdmesp.security.vault.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: connect-login-vss
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.lsdmesp.security.vault.type }}
  mount: {{ .Values.lsdmesp.security.vault.mount }}
  path: {{ .Values.lsdmesp.security.vault.subPath }}/connect-login
  destination:
    name: connect-login
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Values.lsdmesp.security.vault.auth.name }}
{{- else -}}
apiVersion: v1
stringData:
  basic.txt: |-
    username={{ $connect.username }}
    password={{ $connect.password }}
  bearer.txt: |-
    username={{ $connect.username }}
    password={{ $connect.password }}
kind: Secret
metadata:
  name: connect-login
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
