{{- $ksqldb := .Values.lsdmesp.confluent.ksqldb -}}
{{- if $ksqldb.enabled -}}
{{- if .Values.lsdmesp.security.vault.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ksqldb-login-vss
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.lsdmesp.security.vault.type }}
  mount: {{ .Values.lsdmesp.security.vault.mount }}
  path: {{ .Values.lsdmesp.security.vault.subPath }}/ksqldb-login
  destination:
    name: ksqldb-login
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Values.lsdmesp.security.vault.auth.name }}
{{- else -}}
apiVersion: v1
stringData:
  basic.txt: |-
    username={{ $ksqldb.username }}
    password={{ $ksqldb.password }}
  bearer.txt: |-
    username={{ $ksqldb.username }}
    password={{ $ksqldb.password }}
kind: Secret
metadata:
  name: ksqldb-login
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
