apiVersion: v1
stringData:
  mdsPublicKey.pem: |
    {{ .Values.lsdmesp.tls.mds.key }}
  mdsTokenKeyPair.pem: |
    {{ .Values.lsdmesp.tls.mds.publicKey }}
kind: Secret
metadata:
  name: mds-token
  namespace: {{ .Release.Namespace }}
