{{- $schemaregistryy := .Values.lsdmesp.confluent.schemaregistryy -}}
{{- if $schemaregistryy.enabled -}}
apiVersion: v1
stringData:
  basic.txt: |-
    username={{ .Values.lsdmesp.confluent.schemaregistry.username }}
    password={{ .Values.lsdmesp.confluent.schemaregistry.password }}
  bearer.txt: |-
    username={{ .Values.lsdmesp.confluent.schemaregistry.username }}
    password={{ .Values.lsdmesp.confluent.schemaregistry.password }}
kind: Secret
metadata:
  name: schemaregistry-login
  namespace: {{ .Release.Namespace }}
{{- end -}}
