apiVersion: v1
data:
  tls.crt: {{ .Values.lsdmesp.tls.ca.cert | b64enc }}
  tls.key: {{ .Values.lsdmesp.tls.ca.key | b64enc }}
kind: Secret
metadata:
  name: ca-pair-sslcerts
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
