apiVersion: v1
stringData:
  tls.crt: |
    {{ .Values.lsdmesp.tls.ca.cert }}
  tls.key: |
    {{ .Values.lsdmesp.tls.ca.key }}
kind: Secret
metadata:
  name: ca-pair-sslcerts
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
