{{- if .Values.lsdmesp.security.vault.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ca-pair-sslcerts-vss
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.lsdmesp.security.vault.type }}
  mount: {{ .Values.lsdmesp.security.vault.mount }}
  path: {{ .Values.lsdmesp.security.vault.subPath }}/ca-pair-sslcerts
  destination:
    name: ca-pair-sslcerts
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Values.lsdmesp.security.vault.auth.name }}
{{- else -}}
apiVersion: v1
data:
  tls.crt: {{ .Values.lsdmesp.tls.ca.cert | b64enc }}
  tls.key: {{ .Values.lsdmesp.tls.ca.key | b64enc }}
kind: Secret
metadata:
  name: ca-pair-sslcerts
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
{{- end -}}
