apiVersion: v1
data:
  mdsPublicKey.pem: {{ .Values.lsdmesp.tls.mds.key | b64enc }}
  mdsTokenKeyPair.pem: {{ .Values.lsdmesp.tls.mds.publicKey | b64enc }}
kind: Secret
metadata:
  name: mds-token
  namespace: {{ .Release.Namespace }}
