{{- if .Values.lsdmesp.security.vault.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mds-login-vss
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.lsdmesp.security.vault.type }}
  mount: {{ .Values.lsdmesp.security.vault.mount }}
  path: {{ .Values.lsdmesp.security.vault.subPath }}/mds-login
  destination:
    name: mds-login
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Values.lsdmesp.security.vault.auth.name }}
{{- else -}}
apiVersion: v1
stringData:
  ldap.txt: |-
    username=cn={{ .Values.lsdmesp.ldap.readOnlyUser.username }},{{ .Values.lsdmesp.ldap.basedn }}
    password={{ .Values.lsdmesp.ldap.readOnlyUser.password }}
kind: Secret
metadata:
  name: mds-login
  namespace: {{ .Release.Namespace }}
{{- end -}}
