apiVersion: v1
stringData:
  ldap.txt: |-
    username={{ .Values.lsdmesp.ldap.readOnlyUser.username }}
    password={{ .Values.lsdmesp.ldap.readOnlyUser.password }}
kind: Secret
metadata:
  name: mds-login
