apiVersion: v1
stringData:
  ldap.txt: |-
    username=cn={{ .Values.lsdmesp.ldap.readOnlyUser.username }},{{ .Values.lsdmesp.ldap.basedn }}
    password={{ .Values.lsdmesp.ldap.readOnlyUser.password }}
kind: Secret
metadata:
  name: mds-login
  namespace: {{ .Release.Namespace }}
