{{- $controlcenter := .Values.lsdmesp.confluent.controlcenter -}}
{{- if $controlcenter.enabledA -}}
apiVersion: v1
stringData:
  bearer.txt: |-
    username={{ $controlcenter.username }}
    password={{ $controlcenter.password }}
kind: Secret
metadata:
  name: controlcenter-login
  namespace: {{ .Release.Namespace }}
{{- end -}}