apiVersion: v1
stringData:
  bearer.txt: |-
    username={{ .Values.lsdmesp.confluent.kafka.username }}
    password={{ .Values.lsdmesp.confluent.kafka.password }}
kind: Secret
metadata:
  name: kafka-login
