{{- if .Values.lsdmesp.security.vault.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mds-token-vss
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.lsdmesp.security.vault.type }}
  mount: {{ .Values.lsdmesp.security.vault.mount }}
  path: {{ .Values.lsdmesp.security.vault.subPath }}/mds-token
  destination:
    name: mds-token
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Values.lsdmesp.security.vault.auth.name }}
{{- else -}}
apiVersion: v1
data:
  mdsPublicKey.pem: {{ .Values.lsdmesp.tls.mds.publicKey | b64enc }}
  mdsTokenKeyPair.pem: {{ .Values.lsdmesp.tls.mds.key | b64enc }}
kind: Secret
metadata:
  name: mds-token
  namespace: {{ .Release.Namespace }}
{{- end -}}
