{{- $connect := .Values.lsdmesp.confluent.connect -}}
{{- if $connect.enabled -}}
apiVersion: v1
stringData :
  basic.txt: |-
    username={{ $connect.username }}
    password={{ $connect.password }}
  bearer.txt: |-
    username={{ $connect.username }}
    password={{ $connect.password }}
kind: Secret
metadata:
  name: connect-login
{{- end -}}
