{{- $kafkarestclass := .Values.lsdmesp.confluent.kafkarestclass -}}
{{- if $kafkarestclass.enabled -}}
apiVersion: v1
stringData:
  basic.txt: |-
    username={{ $kafkarestclass.username }}
    password={{ $kafkarestclass.password }}
  bearer.txt: |-
    username={{ $kafkarestclass.username }}
    password={{ $kafkarestclass.password }}
kind: Secret
metadata:
  name: kafkarestclass-login
  namespace: {{ .Release.Namespace }}
{{- end -}}
