apiVersion: v1
data:
  basic.txt: dXNlcm5hbWU9Y2Zfa2Fma2EKcGFzc3dvcmQ9dWlHUThpNmdIdkd0
  bearer.txt: dXNlcm5hbWU9Y2Zfa2Fma2EKcGFzc3dvcmQ9dWlHUThpNmdIdkd0
kind: Secret
metadata:
  creationTimestamp: null
  name: kafkarestclass-login
