{{- $kafkarestproxy := .Values.lsdmesp.confluent.kafkarestproxy -}}
{{- if $kafkarestproxy.enabledA -}}
apiVersion: v1
stringData:
  bearer.txt: |-
    username={{ $kafkarestproxy.username }}
    password={{ $kafkarestproxy.password }}
kind: Secret
metadata:
  name: kafkarestproxy-login
  namespace: {{ .Release.Namespace }}
{{- end -}}