{{- $ksqldb := .Values.lsdmesp.confluent.ksqldb -}}
{{- if $ksqldb.enabledA -}}
apiVersion: v1
stringData:
  basic.txt: |-
    username={{ $ksqldb.username }}
    password={{ $ksqldb.password }}
  bearer.txt: |-
    username={{ $ksqldb.username }}
    password={{ $ksqldb.password }}
kind: Secret
metadata:
  name: ksqldb-login
  namespace: {{ .Release.Namespace }}
{{- end -}}