{{- $kraftcontroller := .Values.lsdmesp.confluent.kraftcontroller -}}
{{- if $kraftcontroller.enabled -}}
apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
spec:
  configOverrides:
    jvm:
    - -Xms{{ $kraftcontroller.jvm.Xms }}
    - -Xmx{{ $kraftcontroller.jvm.Xmx }}
  dataVolumeCapacity: {{ $kraftcontroller.dataVolumeCapacity }}
  image:
    application: docker.io/confluentinc/cp-server:{{ .Values.lsdmesp.cpVersion }}
    init: confluentinc/confluent-init-container:{{ .Values.lsdmesp.cpOperatorVersion }}
  listeners:
    controller:
      tls:
        enabled: true
      authentication:
        principalMappingRules:
        - RULE:.*CN[\s]?=[\s]?([a-zA-Z0-9.]*)?.*/$1/
        type: mtls
  oneReplicaPerNode: true
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
    resources:
      {{- toYaml $kraftcontroller.resources | nindent 6 }}
  replicas: {{ $kraftcontroller.replicas }}
  storageClass:
    name: {{ .Values.lsdmesp.storageClass }}
  tls:
    autoGeneratedCerts: true
{{- end -}}
