{{- $kafka := .Values.lsdmesp.confluent.kafka -}}
{{- if $kafka.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-kafka
spec:
  ingressClassName: {{ $kafka.ingress.ingressClassName }}
  rules:
    - host: kafka.{{ $kafka.ingress.baseDomain }}
      http:
        paths:
          - backend:
              service:
                name: kafka
                port:
                  number: 9092
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - kafka.{{ $kafka.ingress.baseDomain }}
      secretName: {{ $kafka.ingress.tls.secretName }}
{{- range $i := until ($kafka.replicas | int) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-kafka-broker-{{ $i }}
{{- with $kafka.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ $kafka.ingress.ingressClassName }}
  rules:
    - host: kafka-broker-{{ $i }}.{{ $kafka.ingress.baseDomain }}
      http:
        paths:
          - backend:
              service:
                name: kafka
                port:
                  number: 9092
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - kafka-broker-{{ $i }}.{{ $kafka.ingress.baseDomain }}
      secretName: {{ $kafka.ingress.tls.secretName }}-{{ $i }}
{{- end -}}
{{- end -}}