{{- $kafka := .Values.lsdmesp.confluent.kafka -}}
{{- if $kafka.enabled -}}
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
spec:
  authorization:
    type: rbac
    superUsers:
      - User:kafka
      - User:cf_kafka
  configOverrides:
    jvm:
    - -Xms{{ $kafka.jvm.Xms }}
    - -Xmx{{ $kafka.jvm.Xmx }}
    server:
    - auto.create.topics.enable=true
    - delete.topic.enable=true
    - num.partitions={{ .Values.lsdmesp.defaultNumPartitions }}
    - min.insync.replicas={{ .Values.lsdmesp.defaultMinInSyncReplicas }}
    - default.replication.factor={{ .Values.lsdmesp.defaultReplicationFactor }}
    - confluent.license.topic.replication.factor={{ .Values.lsdmesp.defaultReplicationFactor }}
    - confluent.license.topic.min.isr={{ .Values.lsdmesp.defaultMinInSyncReplicas }}
    - offsets.topic.replication.factor={{ .Values.lsdmesp.defaultReplicationFactor }}
    - offsets.topic.min.isr={{ .Values.lsdmesp.defaultMinInSyncReplicas }}
    - transaction.state.log.replication.factor={{ .Values.lsdmesp.defaultReplicationFactor }}
    - transaction.state.log.min.isr={{ .Values.lsdmesp.defaultMinInSyncReplicas }}
    - confluent.cluster.link.metadata.topic.replication.factor={{ .Values.lsdmesp.defaultReplicationFactor }}
    - confluent.tier.metadata.replication.factor={{ .Values.lsdmesp.defaultReplicationFactor }}
    - confluent.balancer.topic.replication.factor={{ .Values.lsdmesp.defaultReplicationFactor }}
    - confluent.metadata.topic.replication.factor={{ .Values.lsdmesp.defaultReplicationFactor }}
    - confluent.metrics.reporter.topic.min.isr={{ .Values.lsdmesp.defaultMinInSyncReplicas }}
    - confluent.security.event.logger.exporter.kafka.topic.replicas={{ .Values.lsdmesp.defaultReplicationFactor }}
    - log.retention.ms=86400000
  dataVolumeCapacity: {{ $kafka.dataVolumeCapacity }}
  dependencies:
    kafkaRest:
      authentication:
        type: bearer
        bearer:
          secretRef: kafka-login
    kRaftController:
      clusterRef:
        name: kraftcontroller
      controllerListener:
        tls:
          enabled: true
        authentication:
          principalMappingRules:
          - RULE:.*CN[\s]?=[\s]?([a-zA-Z0-9.]*)?.*/$1/
          type: mtls
  image:
    application: confluentinc/cp-server:{{ .Values.lsdmesp.cpVersion }}
    init: confluentinc/confluent-init-container:{{ .Values.lsdmesp.cpOperatorVersion }}
  listeners:
    internal:
      authentication:
        principalMappingRules:
        - RULE:.*CN[\s]?=[\s]?([a-zA-Z0-9.]*)?.*/$1/
        type: mtls
      tls:
        enabled: true
    replication:
      authentication:
        principalMappingRules:
        - RULE:.*CN[\s]?=[\s]?([a-zA-Z0-9.]*)?.*/$1/
        type: mtls
      tls:
        enabled: true
    external:
      # externalAccess: {} // TODO: Needs to be added 
      authentication:
        type: ldap
      tls:
        enabled: true
  metricReporter:
    authentication:
      type: mtls
    enabled: true
    replicationFactor: {{ .Values.lsdmesp.defaultReplicationFactor }}
    tls:
      enabled: true
  oneReplicaPerNode: true
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
    resources:
      {{- toYaml $kafka.resources | nindent 6 }}
  replicas: {{ $kafka.replicas }}
  services:
    mds:
      # Configure this with TLS encryption, but not with external access through a load balancer.
      # For external access to MDS, an ingress controller can be used.
      tls:
        enabled: true
      tokenKeyPair:
        secretRef: mds-token
      provider:
        type: ldap
        ldap:
          address: ldap://ldap.{{ .Release.Namespace }}.svc.cluster.local:389
          authentication:
            type: simple
            simple:
              secretRef: mds-login
          configurations:
            groupNameAttribute: cn
            groupObjectClass: group
            groupMemberAttribute: member
            groupMemberAttributePattern: CN=(.*),DC=test,DC=com
            groupSearchBase: dc=test,dc=com
            groupSearchScope: 1
            userNameAttribute: cn
            userMemberOfAttributePattern: CN=(.*),DC=test,DC=com
            userObjectClass: organizationalRole
            userSearchBase: dc=test,dc=com
            userSearchScope: 1
  storageClass:
    name: {{ .Values.lsdmesp.storageClass }}
  tls:
    autoGeneratedCerts: true
{{- end -}}
