---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: internal-schemaregistry-0
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_lsdmesp-confluent
  principal:
    name: cf_schemaregistry
    type: user
  role: SecurityAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: internal-schemaregistry-1
  namespace: {{ .Release.Namespace }}
spec:
  principal:
    name: cf_schemaregistry
    type: user
  resourcePatterns:
  - name: _confluent-license
    patternType: LITERAL
    resourceType: Topic
  - name: _confluent-command
    patternType: LITERAL
    resourceType: Topic
  - name: _exporter_configs
    patternType: LITERAL
    resourceType: Topic
  - name: _exporter_states
    patternType: LITERAL
    resourceType: Topic
  - name: _schemas_schemaregistry_lsdmesp-confluent
    patternType: LITERAL
    resourceType: Topic
  - name: id_schemaregistry_lsdmesp-confluent
    patternType: LITERAL
    resourceType: Group
  role: ResourceOwner
