{{- $schemaregistry := .Values.lsdmesp.confluent.schemaregistry -}}
{{- if $schemaregistry.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-schemaregistry
{{- with $schemaregistry.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ $schemaregistry.ingress.ingressClassName }}
  rules:
    - host: schemaregistry.{{ $schemaregistry.ingress.baseDomain }}
      http:
        paths:
          - backend:
              service:
                name: schemaregistry-0-internal
                port:
                  number: 8081
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - schemaregistry.{{ $schemaregistry.ingress.baseDomain }}
      secretName: {{ $schemaregistry.ingress.tls.secretName }}
{{- end -}}