{{- $schemaregistry := .Values.lsdmesp.confluent.schemaregistry -}}
{{- if $schemaregistry.enabled -}}
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: {{ .Release.Namespace }}
  annotations:
    platform.confluent.io/disable-internal-rolebindings-creation: "true"  
spec:
  authorization:
    type: rbac
  configOverrides:
    jvm:
      - -Xms{{ $schemaregistry.jvm.Xms }}
      - -Xmx{{ $schemaregistry.jvm.Xmx }}
  dependencies:
    kafka:
      authentication:
        type: mtls
      bootstrapEndpoint: kafka.{{ .Release.Namespace }}.svc.cluster.local:9071
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.{{ .Release.Namespace }}.svc.cluster.local:8090
      tokenKeyPair:
        directoryPathInContainer: /vault/secrets
      authentication:
        type: bearer
        bearer:
          directoryPathInContainer: /vault/secrets
      tls:
        enabled: true
  image:
    application: confluentinc/cp-schema-registry:{{ .Values.lsdmesp.cpVersion }}
    init: confluentinc/confluent-init-container:{{ .Values.lsdmesp.cpOperatorVersion }}
  internalTopicReplicatorFactor: {{ .Values.lsdmesp.defaultReplicationFactor }}
  {{- if $schemaregistry.externalAccess }}
  listeners:
    external:
      externalAccess: {{ $schemaregistry.externalAccess }}
  {{- end }}
  oneReplicaPerNode: true
  podTemplate:
    serviceAccountName: default
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-run-as-user: "0"
      vault.hashicorp.com/agent-run-as-group: "1000"
      vault.hashicorp.com/agent-inject-secret-schemaregistry-bearer: secret/lsdmesp-confluent/schemaregistry/bearer.txt
      vault.hashicorp.com/agent-inject-file-schemaregistry-bearer: bearer.txt
      vault.hashicorp.com/agent-inject-template-schemaregistry-bearer: |
        {{`{{- with secret "secret/lsdmesp-confluent/schemaregistry/bearer.txt" -}}
        {{ .Data.data.bearer | base64Decode }}{{- end -}}`}}
      vault.hashicorp.com/agent-inject-secret-mds-publickey: secret/lsdmesp-confluent/mds/mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-file-mds-publickey: mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-template-mds-publickey: |
        {{`{{- with secret "secret/lsdmesp-confluent/mds/mdsPublicKey.pem" -}}
        {{ .Data.data.mdspublickey | base64Decode }}{{- end -}}`}}
      vault.hashicorp.com/role: confluent-operator
    probe:
      liveness:
        failureThreshold: 10
        initialDelaySeconds: 30
        periodSeconds: 30
        successThreshold: 1
        timeoutSeconds: 60
      readiness:
        failureThreshold: 10
        initialDelaySeconds: 120
        periodSeconds: 30
        successThreshold: 1
        timeoutSeconds: 60
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      {{- toYaml $schemaregistry.resources | nindent 6 }}
  replicas: {{ $schemaregistry.replicas }}
  tls:
    autoGeneratedCerts: true
{{- end -}}
