{{- $connect := .Values.lsdmesp.confluent.connect -}}
{{- if $connect.enabled -}}
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: {{ .Release.Namespace }}
  annotations:
    platform.confluent.io/disable-internal-rolebindings-creation: "true"  
spec:
  authorization:
    type: rbac
  build:
    onDemand:
      plugins:
        confluentHub:
        - name: kafka-connect-datagen
          owner: confluentinc
          version: 0.6.3
        - name: kafka-connect-jdbc
          owner: confluentinc
          version: 10.7.4
        - name: kafka-connect-http
          owner: confluentinc
          version: 1.7.5
        - name: kafka-connect-elasticsearch
          owner: confluentinc
          version: 14.0.12
        - name: kafka-connect-s3-source
          owner: confluentinc
          version: 2.5.10
        - name: kafka-connect-s3
          owner: confluentinc
          version: 10.5.7
        - name: debezium-connector-mysql
          owner: debezium
          version: 2.2.1
        - name: kafka-connect-elasticsearch-source
          owner: dariobalinzo
          version: 1.5.5
        locationType: confluentHub
    type: onDemand
  configOverrides:
    jvm:
      - -Xms{{ $connect.jvm.Xms }}
      - -Xmx{{ $connect.jvm.Xmx }}
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.{{ .Release.Namespace }}.svc.cluster.local:9071
      authentication:
        type: mtls      
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.{{ .Release.Namespace }}.svc.cluster.local:8090
      tokenKeyPair:
        directoryPathInContainer: /vault/secrets
      authentication:
        type: bearer
        bearer:
          directoryPathInContainer: /vault/secrets
      tls:
        enabled: true
    schemaRegistry:
      tls:
        enabled: true
      url: https://schemaregistry.{{ .Release.Namespace }}.svc.cluster.local:8081
  {{- if $connect.externalAccess }}
  externalAccess: {{ $connect.externalAccess }}
  {{- end }}
  image:
    application: confluentinc/cp-server-connect:{{ .Values.lsdmesp.cpVersion }}
    init: confluentinc/confluent-init-container:{{ .Values.lsdmesp.cpOperatorVersion }}
  internalTopicReplicationFactor: {{ .Values.lsdmesp.defaultReplicationFactor }}
  oneReplicaPerNode: true
  podTemplate:
    serviceAccountName: default
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-run-as-user: "0"
      vault.hashicorp.com/agent-run-as-group: "1000"
      vault.hashicorp.com/agent-inject-secret-connect-bearer: secret/lsdmesp-confluent/connect/bearer.txt
      vault.hashicorp.com/agent-inject-file-connect-bearer: bearer.txt
      vault.hashicorp.com/agent-inject-template-connect-bearer: |
        {{`{{- with secret "secret/lsdmesp-confluent/connect/bearer.txt" -}}
        {{ .Data.data.bearer | base64Decode }}{{- end -}}`}}
      vault.hashicorp.com/agent-inject-secret-mds-publickey: secret/lsdmesp-confluent/mds/mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-file-mds-publickey: mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-template-mds-publickey: |
        {{`{{- with secret "secret/lsdmesp-confluent/mds/mdsPublicKey.pem" -}}
        {{ .Data.data.mdspublickey | base64Decode }}{{- end -}}`}}
      vault.hashicorp.com/role: confluent-operator
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      {{- toYaml $connect.resources | nindent 6 }}
  replicas: {{ $connect.replicas }}
  tls:
    autoGeneratedCerts: true      
{{- end -}}
