{{- $connect := .Values.lsdmesp.confluent.connect -}}
{{- if $connect.enabled -}}
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: {{ .Release.Namespace }}
spec:
  authorization:
    type: rbac
  build:
    onDemand:
      plugins:
        confluentHub:
        - name: kafka-connect-datagen
          owner: confluentinc
          version: 0.6.3
        - name: kafka-connect-jdbc
          owner: confluentinc
          version: 10.7.4
        - name: kafka-connect-http
          owner: confluentinc
          version: 1.7.5
        - name: kafka-connect-elasticsearch
          owner: confluentinc
          version: 14.0.12
        - name: kafka-connect-s3-source
          owner: confluentinc
          version: 2.5.10
        - name: kafka-connect-s3
          owner: confluentinc
          version: 10.5.7
        - name: debezium-connector-mysql
          owner: debezium
          version: 2.2.1
        - name: kafka-connect-elasticsearch-source
          owner: dariobalinzo
          version: 1.5.5
        locationType: confluentHub
    type: onDemand
  configOverrides:
    jvm:
      - -Xms{{ $connect.jvm.Xms }}
      - -Xmx{{ $connect.jvm.Xmx }}
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.{{ .Release.Namespace }}.svc.cluster.local:9071
      authentication:
        type: mtls      
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.{{ .Release.Namespace }}.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: connect-login
      tls:
        enabled: true
    schemaRegistry:
      tls:
        enabled: true
      url: https://schemaregistry.{{ .Release.Namespace }}.svc.cluster.local:8081
  image:
    application: confluentinc/cp-server-connect:{{ .Values.lsdmesp.cpVersion }}
    init: confluentinc/confluent-init-container:{{ .Values.lsdmesp.cpOperatorVersion }}
  internalTopicReplicationFactor: {{ .Values.lsdmesp.defaultReplicationFactor }}
  oneReplicaPerNode: true
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      {{- toYaml $connect.resources | nindent 6 }}
  replicas: {{ $connect.replicas }}
  tls:
    autoGeneratedCerts: true      
{{- end -}}
