{{- $connect := .Values.lsdmesp.confluent.connect -}}
{{- if $connect.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-connect
{{- with $connect.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ $connect.ingress.ingressClassName }}
  rules:
    - host: connect.{{ $connect.ingress.baseDomain }}
      http:
        paths:
          - backend:
              service:
                name: connect-0-internal
                port:
                  number: 8083
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - connect.{{ $connect.ingress.baseDomain }}
      secretName: {{ $connect.ingress.tls.secretName }}
{{- end -}}