{{- $ksqldb := .Values.lsdmesp.confluent.ksqldb -}}
{{- if $ksqldb.enabled -}}
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: {{ .Release.Namespace }}
  annotations:
    platform.confluent.io/disable-internal-rolebindings-creation: "true"  
spec:
  authorization:
    type: rbac
  configOverrides:
    jvm:
      - -Xms{{ $ksqldb.jvm.Xms }}
      - -Xmx{{ $ksqldb.jvm.Xmx }}
    server:
      - ksql.internal.topic.replicas={{ .Values.lsdmesp.defaultReplicationFactor }}
      - ksql.logging.processing.topic.replication.factor={{ .Values.lsdmesp.defaultReplicationFactor }}
  dataVolumeCapacity: {{ $ksqldb.dataVolumeCapacity }}
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.{{ .Release.Namespace }}.svc.cluster.local:9071
      authentication:
        type: mtls      
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.{{ .Release.Namespace }}.svc.cluster.local:8090
      tokenKeyPair:
        directoryPathInContainer: /vault/secrets
      authentication:
        type: bearer
        bearer:
          directoryPathInContainer: /vault/secrets
      tls:
        enabled: true
    schemaRegistry:
      tls:
        enabled: true
      url: https://schemaregistry.{{ .Release.Namespace }}.svc.cluster.local:8081
    connect:
      tls:
        enabled: true
      url: https://connect.{{ .Release.Namespace }}.svc.cluster.local:8083
  image:
    application: confluentinc/cp-ksqldb-server:{{ .Values.lsdmesp.cpVersion }}
    init: confluentinc/confluent-init-container:{{ .Values.lsdmesp.cpOperatorVersion }}
  internalTopicReplicationFactor: {{ .Values.lsdmesp.defaultReplicationFactor }}
  {{- if $ksqldb.externalAccess }}
  listeners:
    external:
      externalAccess: {{ $ksqldb.externalAccess }}
  {{- end }}
  oneReplicaPerNode: true
  podTemplate:
    serviceAccountName: default
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-run-as-user: "0"
      vault.hashicorp.com/agent-run-as-group: "1000"
      vault.hashicorp.com/agent-inject-secret-ksqldb-bearer: secret/lsdmesp-confluent/ksqldb/bearer.txt
      vault.hashicorp.com/agent-inject-file-ksqldb-bearer: bearer.txt
      vault.hashicorp.com/agent-inject-template-ksqldb-bearer: |
        {{`{{- with secret "secret/lsdmesp-confluent/ksqldb/bearer.txt" -}}
        {{ .Data.data.bearer | base64Decode }}{{- end -}}`}}
      vault.hashicorp.com/agent-inject-secret-mds-publickey: secret/lsdmesp-confluent/mds/mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-file-mds-publickey: mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-template-mds-publickey: |
        {{`{{- with secret "secret/lsdmesp-confluent/mds/mdsPublicKey.pem" -}}
        {{ .Data.data.mdspublickey | base64Decode }}{{- end -}}`}}
      vault.hashicorp.com/role: confluent-operator
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      {{- toYaml $ksqldb.resources | nindent 6 }}
  replicas: {{ $ksqldb.replicas }}
  storageClass:
    name: {{ .Values.lsdmesp.storageClass }}
  tls:
    autoGeneratedCerts: true
{{- end -}}