{{- $kafkarestproxy := .Values.lsdmesp.confluent.kafkarestproxy -}}
{{- if $kafkarestproxy.enabled -}}
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: {{ .Release.Namespace }}
spec:
  authorization:
    type: rbac
  configOverrides:
    jvm:
      - -Xms{{ $kafkarestproxy.jvm.Xms }}
      - -Xmx{{ $kafkarestproxy.jvm.Xmx }}
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.{{ .Release.Namespace }}.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.{{ .Release.Namespace }}.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: kafkarestproxy-login
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.{{ .Release.Namespace }}.svc.cluster.local:8081
      tls:
        enabled: true
  image:
    application: confluentinc/cp-kafka-rest:{{ .Values.lsdmesp.cpVersion }}
    init: confluentinc/confluent-init-container:{{ .Values.lsdmesp.cpOperatorVersion }}
  oneReplicaPerNode: true
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      {{- toYaml $kafkarestproxy.resources | nindent 6 }}
  replicas: {{ $kafkarestproxy.replicas }}
  tls:
    autoGeneratedCerts: true
{{- end -}}
