{{- $kafkarestproxy := .Values.lsdmesp.confluent.kafkarestproxy -}}
{{- if $kafkarestproxy.enabled -}}
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: {{ .Release.Namespace }}
spec:
  authorization:
    type: rbac
  configOverrides:
    server:
      - metrics.jmx.prefix=kafka.rest
    jvm:
      - -Xms{{ $kafkarestproxy.jvm.Xms }}
      - -Xmx{{ $kafkarestproxy.jvm.Xmx }}
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.{{ .Release.Namespace }}.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.{{ .Release.Namespace }}.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: kafkarestproxy-login
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.{{ .Release.Namespace }}.svc.cluster.local:8081
      tls:
        enabled: true
  image:
    application: confluentinc/cp-kafka-rest:{{ .Values.lsdmesp.cpVersion }}
    init: confluentinc/confluent-init-container:{{ .Values.lsdmesp.cpOperatorVersion }}
  oneReplicaPerNode: true
  metrics:
    prometheus:
      rules:
        # "kafka.rest:type=jetty-metrics"
        - pattern: "kafka.rest<type=jetty-metrics>([^:]+):"
          name: "kafka_rest_jetty_metrics_$1"
        # "kafka.rest:type=jersey-metrics"
        - pattern: "kafka.rest<type=jersey-metrics>([^:]+):"
          name: "kafka_rest_jersey_metrics_$1"
        # "kafka.rest:type=consumer-node-metrics,client-id=*,node-id=*,"
        # "kafka.rest:type=producer-node-metrics,client-id=*,node-id=*,"
        - pattern: "kafka.rest<type=(.+), client-id=(.+), node-id=node-(.+)><>(.+): (.+)"
          name: "kafka_rest_$1_$4"
          type: GAUGE
          cache: true
          labels:
            client_id: $2
            node_id: $3
        # "kafka.rest:type=consumer-metrics,client-id=*"
        # "kafka.rest:type=producer-metrics,client-id=*"
        - pattern: "kafka.rest<type=(.+), client-id=(.+)><>(.+): (.+)"
          name: "kafka_rest_$1_$3"
          type: GAUGE
          cache: true
          labels:
            client_id: $2
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      {{- toYaml $kafkarestproxy.resources | nindent 6 }}
  replicas: {{ $kafkarestproxy.replicas }}
  tls:
    autoGeneratedCerts: true
{{- end -}}
