{{- $kafkarestproxy := .Values.lsdmesp.confluent.kafkarestproxy -}}
{{- if $kafkarestproxy.enabled -}}
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: {{ .Release.Namespace }}
  annotations:
    platform.confluent.io/disable-internal-rolebindings-creation: "true"  
spec:
  authorization:
    type: rbac
  configOverrides:
    jvm:
      - -Xms{{ $kafkarestproxy.jvm.Xms }}
      - -Xmx{{ $kafkarestproxy.jvm.Xmx }}
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.{{ .Release.Namespace }}.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.{{ .Release.Namespace }}.svc.cluster.local:8090
      tokenKeyPair:
        directoryPathInContainer: /vault/secrets
      authentication:
        type: bearer
        bearer:
          directoryPathInContainer: /vault/secrets
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.{{ .Release.Namespace }}.svc.cluster.local:8081
      tls:
        enabled: true
  image:
    application: confluentinc/cp-kafka-rest:{{ .Values.lsdmesp.cpVersion }}
    init: confluentinc/confluent-init-container:{{ .Values.lsdmesp.cpOperatorVersion }}
  oneReplicaPerNode: true
  podTemplate:
    serviceAccountName: default
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-run-as-user: "0"
      vault.hashicorp.com/agent-run-as-group: "1000"
      vault.hashicorp.com/agent-inject-secret-kafkarestproxy-bearer: secret/lsdmesp-confluent/kafkarestproxy/bearer.txt
      vault.hashicorp.com/agent-inject-file-kafkarestproxy-bearer: bearer.txt
      vault.hashicorp.com/agent-inject-template-kafkarestproxy-bearer: |
        {{`{{- with secret "secret/lsdmesp-confluent/kafkarestproxy/bearer.txt" -}}
        {{ .Data.data.bearer | base64Decode }}{{- end -}}`}}
      vault.hashicorp.com/agent-inject-secret-mds-publickey: secret/lsdmesp-confluent/mds/mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-file-mds-publickey: mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-template-mds-publickey: |
        {{`{{- with secret "secret/lsdmesp-confluent/mds/mdsPublicKey.pem" -}}
        {{ .Data.data.mdspublickey | base64Decode }}{{- end -}}`}}
      vault.hashicorp.com/role: confluent-operator
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      {{- toYaml $kafkarestproxy.resources | nindent 6 }}
  replicas: {{ $kafkarestproxy.replicas }}
  tls:
    autoGeneratedCerts: true
{{- end -}}
