{{- $controlcenter := .Values.lsdmesp.confluent.controlcenter -}}
{{- if $controlcenter.enabled -}}
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: {{ .Release.Namespace }}
  annotations:
    platform.confluent.io/disable-internal-rolebindings-creation: "true"  
spec:
  authorization:
    type: rbac
  configOverrides:
    jvm:
      - -Xms{{ $controlcenter.jvm.Xms }}
      - -Xmx{{ $controlcenter.jvm.Xmx }}
    server:
      - confluent.controlcenter.internal.topics.retention.ms=21600000
      - confluent.metrics.topic.retention.ms=21600000
      - confluent.monitoring.interceptor.topic.retention.ms=21600000
      # - confluent.controlcenter.rest.advertised.url=https://controlcenter.some.domain
  dataVolumeCapacity: {{ $controlcenter.dataVolumeCapacity }}
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.{{ .Release.Namespace }}.svc.cluster.local:9071
      authentication:
        type: mtls      
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.{{ .Release.Namespace }}.svc.cluster.local:8090
      tokenKeyPair:
        directoryPathInContainer: /vault/secrets
      authentication:
        type: bearer
        bearer:
          directoryPathInContainer: /vault/secrets
      tls:
        enabled: true
    schemaRegistry:
      tls:
        enabled: true
      url: https://schemaregistry.{{ .Release.Namespace }}.svc.cluster.local:8081
    connect:
    - name: connect
      tls:
        enabled: true
      url: https://connect.{{ .Release.Namespace }}.svc.cluster.local:8083
    ksqldb:
    - name: ksqldb
      # Is this needed? advertisedUrl: https://ksqldb.{{ .Release.Namespace }}.apps.some.domain:443
      tls:
        enabled: true
      url: https://ksqldb.{{ .Release.Namespace }}.svc.cluster.local:8088
  {{- if $controlcenter.externalAccess }}
  externalAccess: {{ $controlcenter.externalAccess }}
  {{- end }}
  image:
    application: confluentinc/cp-enterprise-control-center:{{ .Values.lsdmesp.cpVersion }}
    init: confluentinc/confluent-init-container:{{ .Values.lsdmesp.cpOperatorVersion }}
  internalTopicReplicatorFactor: {{ .Values.lsdmesp.defaultReplicationFactor }}
  podTemplate:
    serviceAccountName: default
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-run-as-user: "0"
      vault.hashicorp.com/agent-run-as-group: "1000"
      vault.hashicorp.com/agent-inject-secret-controlcenter-bearer: secret/lsdmesp-confluent/controlcenter/bearer.txt
      vault.hashicorp.com/agent-inject-file-controlcenter-bearer: bearer.txt
      vault.hashicorp.com/agent-inject-template-controlcenter-bearer: |
        {{`{{- with secret "secret/lsdmesp-confluent/controlcenter/bearer.txt" -}}
        {{ .Data.data.bearer | base64Decode }}{{- end -}}`}}
      vault.hashicorp.com/agent-inject-secret-mds-publickey: secret/lsdmesp-confluent/mds/mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-file-mds-publickey: mdsPublicKey.pem
      vault.hashicorp.com/agent-inject-template-mds-publickey: |
        {{`{{- with secret "secret/lsdmesp-confluent/mds/mdsPublicKey.pem" -}}
        {{ .Data.data.mdspublickey | base64Decode }}{{- end -}}`}}
      vault.hashicorp.com/role: confluent-operator
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      {{- toYaml $controlcenter.resources | nindent 6 }}
  replicas: {{ $controlcenter.replicas }}
  storageClass:
    name: {{ .Values.lsdmesp.storageClass }}
  tls:
    autoGeneratedCerts: true      
{{- end -}}
