apiVersion: platform.confluent.io/v1beta1
kind: CMFRestClass
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  cmfRest:
    endpoint: https://cmf-service.{{ .Release.Namespace }}.svc.cluster.local:80
    authentication:
      type: mtls
      sslClientAuthentication: true
    tls:
      secretRef: cmf-day2-tls
