apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-ksqldb-0
  namespace: {{ .Release.Namespace }}
spec:
  principal:
    name: cf_ksqldb
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-ksqldb-1
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    connectClusterId: {{ .Release.Namespace }}.connect
  principal:
    name: cf_ksqldb
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-ksqldb-2
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_{{ .Release.Namespace }}
  principal:
    name: cf_ksqldb
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-connect-0
  namespace: {{ .Release.Namespace }}
spec:
  principal:
    name: cf_connect
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-connect-1
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    connectClusterId: {{ .Release.Namespace }}.connect
  principal:
    name: cf_connect
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-connect-2
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_{{ .Release.Namespace }}
  principal:
    name: cf_connect
    type: user
  role: SystemAdmin
