apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-0
spec:
  principal:
    name: cf_kafka
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-1
spec:
  clustersScopeByIds:
    connectClusterId: {{ .Release.Namespace }}.connect
  principal:
    name: cf_kafka
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-2
spec:
  clustersScopeByIds:
    ksqlClusterId: {{ .Release.Namespace }}.ksqldb_
  principal:
    name: cf_kafka
    type: user
  resourcePatterns:
  - name: ksql-cluster
    patternType: LITERAL
    resourceType: KsqlCluster
  role: ResourceOwner
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-3
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_{{ .Release.Namespace }}
  principal:
    name: cf_kafka
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-4
spec:
  principal:
    name: cf_ksqldb
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-5
spec:
  clustersScopeByIds:
    connectClusterId: {{ .Release.Namespace }}.connect
  principal:
    name: cf_ksqldb
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-6
spec:
  clustersScopeByIds:
    ksqlClusterId: {{ .Release.Namespace }}.ksqldb_
  principal:
    name: cf_ksqldb
    type: user
  resourcePatterns:
  - name: ksql-cluster
    patternType: LITERAL
    resourceType: KsqlCluster
  role: ResourceOwner
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-7
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_{{ .Release.Namespace }}
  principal:
    name: cf_ksqldb
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-8
spec:
  principal:
    name: cf_connect
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-9
spec:
  clustersScopeByIds:
    connectClusterId: {{ .Release.Namespace }}.connect
  principal:
    name: cf_connect
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-10
spec:
  clustersScopeByIds:
    ksqlClusterId: {{ .Release.Namespace }}.ksqldb_
  principal:
    name: cf_connect
    type: user
  resourcePatterns:
  - name: ksql-cluster
    patternType: LITERAL
    resourceType: KsqlCluster
  role: ResourceOwner
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-11
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_{{ .Release.Namespace }}
  principal:
    name: cf_connect
    type: user
  role: SystemAdmin
