apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-0
  namespace: {{ .Release.Namespace }}
spec:
  principal:
    name: cf_kafka
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-1
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    connectClusterId: {{ .Release.Namespace }}.connect
  principal:
    name: cf_kafka
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-2
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    ksqlClusterId: {{ .Release.Namespace }}.ksqldb_
  principal:
    name: cf_kafka
    type: user
  resourcePatterns:
  - name: ksql-cluster
    patternType: LITERAL
    resourceType: KsqlCluster
  role: ResourceOwner
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-3
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_{{ .Release.Namespace }}
  principal:
    name: cf_kafka
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-4
  namespace: {{ .Release.Namespace }}
spec:
  principal:
    name: cf_ksqldb
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-5
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    connectClusterId: {{ .Release.Namespace }}.connect
  principal:
    name: cf_ksqldb
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-6
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    ksqlClusterId: {{ .Release.Namespace }}.ksqldb_
  principal:
    name: cf_ksqldb
    type: user
  resourcePatterns:
  - name: ksql-cluster
    patternType: LITERAL
    resourceType: KsqlCluster
  role: ResourceOwner
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-7
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_{{ .Release.Namespace }}
  principal:
    name: cf_ksqldb
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-8
  namespace: {{ .Release.Namespace }}
spec:
  principal:
    name: cf_connect
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-9
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    connectClusterId: {{ .Release.Namespace }}.connect
  principal:
    name: cf_connect
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-10
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    ksqlClusterId: {{ .Release.Namespace }}.ksqldb_
  principal:
    name: cf_connect
    type: user
  resourcePatterns:
  - name: ksql-cluster
    patternType: LITERAL
    resourceType: KsqlCluster
  role: ResourceOwner
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: lsdmesp-sysadmin-11
  namespace: {{ .Release.Namespace }}
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: id_schemaregistry_{{ .Release.Namespace }}
  principal:
    name: cf_connect
    type: user
  role: SystemAdmin
