{{- $ldap := .Values.lsdmesp.ldap -}}
{{- if $ldap.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ldap
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: ldap
  serviceName: "ldap"
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: ldap
        args:
        - --copy-service
        - --loglevel=debug
        imagePullPolicy: IfNotPresent
        image: {{ $ldap.image }}
        ports:
        - containerPort: 389
          name: ldap
        - containerPort: 636
          name: ldaps
        env:
        {{- if $ldap.tls.enabled }}
        - name: LDAP_TLS_VERIFY_CLIENT
          value: try
        - name: LDAP_TLS_CRT_FILENAME
          value: tls.crt
        - name: LDAP_TLS_KEY_FILENAME
          value: tls.key
        - name: LDAP_TLS_CA_CRT_FILENAME
          value: ca.crt
        {{- end }}
        - name: LDAP_TLS
          value: "{{ $ldap.tls.enabled }}"
        - name: LDAP_READONLY_USER
          value: "true"
        - name: LDAP_READONLY_USER_USERNAME
          value: $ldap.readOnlyUser.username
        - name: LDAP_READONLY_USER_PASSWORD
          value: $ldap.readOnlyUser.password
        - name: LDAP_ORGANISATION
          value: $ldap.organisation
        - name: LDAP_DOMAIN
          value: $ldap.domain
        - name: LDAP_ADMIN_PASSWORD
          value: $ldap.admin_password
        - name: LDAP_CONFIG_PASSWORD
          value: $ldap.config_password
        - name: LDAP_BASE_DN
          value: $ldap.basedn
        {{- range $key, $val := $ldap.env }}
        {{ printf "- name: %s" $key }}
        {{ printf "  value: \"%s\"" $val }}
        {{- end }}
        volumeMounts:
        {{- if $ldap.tls.enabled }}
        - mountPath: /container/service/slapd/assets/certs
          name: sslcerts-volume
        {{- end }}
        - mountPath: /var/lib/ldap
          name: ldap-data
        - mountPath: /etc/ldap/slapd.d
          name: ldap-config
        - mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
          name: customldif
      volumes:
      {{- if $ldap.tls.enabled }}
      - name: sslcerts-volume
        secret:
          defaultMode: 420
          secretName: {{ .Release.Name }}-sslcerts
      {{- end }}
      - name: customldif
        secret:
          defaultMode: 420
          secretName: {{ .Release.Name }}-ldifs
  volumeClaimTemplates:
  - metadata:
      name: ldap-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 500Mi
  - metadata:
      name: ldap-config
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 500Mi
{{- end }}
