{{- if .Values.lsdmesp.ldap.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.name }}-ldifs
  namespace: {{ .Release.Namespace }}
stringData:
  00_cf_connect.ldif: |-
    dn: cn=cf_connect,{{ LDAP_BASE_DN }}
    userPassword: {{ .Values.lsdmesp.confluent.connect.password }}
    description: Confluent Connect user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: {{ .Values.lsdmesp.confluent.connect.username }}
  01_cf_controlcenter.ldif: |-
    dn: cn=cf_controlcenter,{{ LDAP_BASE_DN }}
    userPassword: {{ .Values.lsdmesp.confluent.controlcenter.password }}
    description: Confluent Control Center user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: {{ .Values.lsdmesp.confluent.controlcenter.username }}
  02_cf_kafka.ldif: |-
    dn: cn=cf_kafka,{{ LDAP_BASE_DN }}
    userPassword: {{ .Values.lsdmesp.confluent.kafka.password }}
    description: Confluent Kafka user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: {{ .Values.lsdmesp.confluent.kafka.username }}
  03_cf_restproxy.ldif: |-
    dn: cn=cf_restproxy,{{ LDAP_BASE_DN }}
    userPassword: {{ .Values.lsdmesp.confluent.restproxy.password }}
    description: Confluent REST Proxy user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: {{ .Values.lsdmesp.confluent.restproxy.username }}
  04_cf_ksqldb.ldif: |-
    dn: cn=cf_ksqldb,{{ LDAP_BASE_DN }}
    userPassword: {{ .Values.lsdmesp.confluent.ksqldb.password }}
    description: Confluent ksqlDB user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: {{ .Values.lsdmesp.confluent.ksqldb.username }}
  05_cf_schemaregistry.ldif: |-
    dn: cn=cf_schemaregistry,{{ LDAP_BASE_DN }}
    userPassword: {{ .Values.lsdmesp.confluent.schemaregistry.password }}
    description: Confluent Schema Registry user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: {{ .Values.lsdmesp.confluent.schemaregistry.username }}
{{- range $key, $val := .Values.lsdmesp.ldap.extra_ldifs }}
  {{ $key }}: |-
{{ $val | indent 4 }}
{{- end }}
---
{{- if .Values.lsdmesp.ldap.tls.enabled -}}
apiVersion: v1
stringData:
  tls.crt: "{{ .Values.lsdmesp.ldap.tls.fullchain }}"
  tls.key: "{{ .Values.lsdmesp.ldap.tls.privkey }}"
  ca.crt: "{{ .Values.lsdmesp.ldap.tls.cacerts }}"
kind: Secret
metadata:
  name: {{ .Release.name }}-sslcerts
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
{{- end }}
{{- end }}