{{- if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{- else }}
apiVersion: apps/v1beta2
{{- end }}
kind: Deployment
metadata:
  name: {{ template "cp-kafka-connect.fullname" . }}
  labels:
    app: {{ template "cp-kafka-connect.name" . }}
    chart: {{ template "cp-kafka-connect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "cp-kafka-connect.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cp-kafka-connect.name" . }}
        release: {{ .Release.Name }}
      {{- if or .Values.podAnnotations .Values.prometheus.jmx.enabled }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- if .Values.prometheus.jmx.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.prometheus.jmx.port | quote }}
      {{- end }}
      {{- end }}
    spec:
      containers:
        {{- if .Values.prometheus.jmx.enabled }}
        - name: prometheus-jmx-exporter
          image: "{{ .Values.prometheus.jmx.image }}:{{ .Values.prometheus.jmx.imageTag }}"
          imagePullPolicy: "{{ .Values.prometheus.jmx.imagePullPolicy }}"
          command:
          - java
          - -XX:+UnlockExperimentalVMOptions
          - -XX:+UseCGroupMemoryLimitForHeap
          - -XX:MaxRAMFraction=1
          - -XshowSettings:vm
          - -jar
          - jmx_prometheus_httpserver.jar
          - {{ .Values.prometheus.jmx.port | quote }}
          - /etc/jmx-kafka-connect/jmx-kafka-connect-prometheus.yml
          ports:
          - containerPort: {{ .Values.prometheus.jmx.port }}
          resources:
{{ toYaml .Values.prometheus.jmx.resources | indent 12 }}
          volumeMounts:
          - name: jmx-config
            mountPath: /etc/jmx-kafka-connect
        {{- end }}
        - name: {{ template "cp-kafka-connect.name" . }}-server
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - name: kafka-connect
              containerPort: {{ .Values.servicePort}}
              protocol: TCP
            {{- if .Values.prometheus.jmx.enabled }}
            - containerPort: {{ .Values.jmx.port }}
              name: jmx
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if .Values.restSecurity.tls.enabled }}
            - name: CONNECT_LISTENERS
              value: https://0.0.0.0:{{ .Values.servicePort }}
            - name: CONNECT_LISTENERS_HTTPS_SSL_TRUSTSTORE_LOCATION
              value: "/opt/kafka/basicauth/truststore.p12"
            - name: CONNECT_LISTENERS_HTTPS_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lsdmesp-tls
                  key: password
            - name: CONNECT_LISTENERS_HTTPS_SSL_KEYSTORE_LOCATION
              value: "/opt/kafka/basicauth/keystore.p12"
            - name: CONNECT_LISTENERS_HTTPS_SSL_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lsdmesp-tls
                  key: password
            - name: CONNECT_LISTENERS_HTTPS_SSL_KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lsdmesp-tls
                  key: password
            {{- else }}
            - name: CONNECT_LISTENERS
              value: http://0.0.0.0:{{ .Values.servicePort }}
            {{- end }}
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: {{ template "cp-kafka-connect.kafka.bootstrapServers" . }}
            - name: CONNECT_GROUP_ID
              value: {{ template "cp-kafka-connect.groupId" . }}
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: {{ template "cp-kafka-connect.fullname" . }}-config
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: {{ template "cp-kafka-connect.fullname" . }}-offset
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: {{ template "cp-kafka-connect.fullname" . }}-status
            - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
              value: {{ template "cp-kafka-connect.cp-schema-registry.service-name" .}}
            - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
              value: {{ template "cp-kafka-connect.cp-schema-registry.service-name" .}}
            - name: KAFKA_HEAP_OPTS
              value: "{{ .Values.heapOptions }}"
            {{- if .Values.kafkaConnectOpts }}
            - name: KAFKA_OPTS
              value: "{{ .Values.kafkaConnectOpts }}"
            {{- end }}
            - name: CONNECT_CONFIG_PROVIDERS_FILE_CLASS
              value: "org.apache.kafka.common.config.provider.FileConfigProvider"
            - name: CONNECT_CONFIG_PROVIDERS
              value: "file"
            - name: CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY
              value: "All"
            {{- if .Values.restSecurity.basic.enabled }}
            - name: CONNECT_REST_EXTENSION_CLASSES
              value: "org.apache.kafka.connect.rest.basic.auth.extension.BasicAuthSecurityRestExtension"
            - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_CREDENTIALS_SOURCE
              value: "USER_INFO"
            - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO
              valueFrom:
                secretKeyRef:
                  name: lsdmesp-api
                  key: user-info
            - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_CREDENTIALS_SOURCE
              value: "USER_INFO"
            - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO
              valueFrom:
                secretKeyRef:
                  name: lsdmesp-api
                  key: user-info
            {{- end }}
            {{- if .Values.internalSecurity.enabled }}
            - name: CONNECT_SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: CONNECT_SASL_MECHANISM
              value: "SCRAM-SHA-512"
            - name: CONNECT_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: lsdmesp
                  key: sasl.jaas.config
            - name: CONNECT_SSL_TRUSTSTORE_LOCATION
              value: "/opt/kafka/certs-cluster-ca/ca.p12"
            - name: CONNECT_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lsdmesp-cluster-ca-cert
                  key: ca.password
            - name: CONNECT_CONSUMER_SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: CONNECT_CONSUMER_SASL_MECHANISM
              value: "SCRAM-SHA-512"
            - name: CONNECT_CONSUMER_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: lsdmesp
                  key: sasl.jaas.config
            - name: CONNECT_CONSUMER_SSL_TRUSTSTORE_LOCATION
              value: "/opt/kafka/certs-cluster-ca/ca.p12"
            - name: CONNECT_CONSUMER_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lsdmesp-cluster-ca-cert
                  key: ca.password
            - name: CONNECT_PRODUCER_SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: CONNECT_PRODUCER_SASL_MECHANISM
              value: "SCRAM-SHA-512"
            - name: CONNECT_PRODUCER_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: lsdmesp
                  key: sasl.jaas.config
            - name: CONNECT_PRODUCER_SSL_TRUSTSTORE_LOCATION
              value: "/opt/kafka/certs-cluster-ca/ca.p12"
            - name: CONNECT_PRODUCER_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lsdmesp-cluster-ca-cert
                  key: ca.password
            {{- end }}
            {{- if .Values.restSecurity.tls.enabled }}
            - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION
              value: "/opt/kafka/basicauth/truststore.p12"
            - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lsdmesp-tls
                  key: password
            - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION
              value: "/opt/kafka/basicauth/truststore.p12"
            - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lsdmesp-tls
                  key: password
            {{- end }}
            {{- range $key, $value := .Values.configurationOverrides }}
            - name: {{ printf "CONNECT_%s" $key | replace "." "_" | upper | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.customEnv }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.jmx.port }}
            - name: KAFKA_JMX_PORT
              value: "{{ .Values.jmx.port }}"
            {{- end }}
        {{- if .Values.customEnv.CUSTOM_SCRIPT_PATH }}
          command:
            - /bin/bash
            - -c
            - |
              /etc/confluent/docker/run &
              $CUSTOM_SCRIPT_PATH
              sleep infinity
          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | trim | indent 12 }}
          {{- end }}
        {{- end }}
          volumeMounts:
          {{- if .Values.restSecurity.basic.enabled }}
            - name: lsdmesp-jaas-config
              mountPath: /opt/kafka/jaas-config
            - name: lsdmesp-passwords
              mountPath: /opt/kafka/lsdmesp-passwords
          {{- end }}
          {{- if .Values.internalSecurity.enabled }}
            - name: lsdmesp
              mountPath: /opt/kafka/certs-lsdmesp
          {{- end }}
          {{- if .Values.internalSecurity.enabled }}
            - name: lsdmesp-cluster-ca-cert
              mountPath: /opt/kafka/certs-cluster-ca
          {{- end }}
          {{- if .Values.restSecurity.tls.enabled }}
            - name: lsdmesp-tls
              mountPath: /opt/kafka/basicauth
          {{- end }}
          {{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 10 }}
          {{- end}}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.restSecurity.basic.enabled }}
      - name: lsdmesp-jaas-config
        configMap:
          name: lsdmesp-jaas-config
      - secret:
          defaultMode: 420
          secretName: lsdmesp-passwords
        name: lsdmesp-passwords
      {{- end }}
      {{- if .Values.internalSecurity.enabled }}
      - name: lsdmesp
        secret:
          defaultMode: 292
          secretName: lsdmesp
      {{- end }}
      {{- if .Values.internalSecurity.enabled }}
      - name: lsdmesp-cluster-ca-cert
        secret:
          defaultMode: 292
          secretName: lsdmesp-cluster-ca-cert
      {{- end }}
      {{- if .Values.restSecurity.tls.enabled }}
      - name: lsdmesp-tls
        secret:
          defaultMode: 292
          secretName: lsdmesp-tls
      {{- end }}
      {{- if .Values.volumes }}
{{ toYaml .Values.volumes | trim | indent 6 }}
      {{- end}}
      {{- if .Values.prometheus.jmx.enabled }}
      - name: jmx-config
        configMap:
          name: {{ template "cp-kafka-connect.fullname" . }}-jmx-configmap
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
