---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  labels:
    app: microservice
spec:
  replicas: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: microservice
          # image: mkananizadeh/appmod-microservice
          image: lsdtrip/appmod-microservice:0.1.0
          env:
            - name: BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: BOOTSTRAP_SERVERS
            - name: SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: CLIENT_KEY
            - name: SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: CLIENT_SECRET
            - name: SASL_MECHANISM
              value: "PLAIN"
            - name: SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: KSQLDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KSQLDB_API_KEY
            - name: KSQLDB_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KSQLDB_API_SECRET
            - name: KSQLDB_APP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: KSQLDB_APP_ENDPOINT
            - name: SSL_CA_LOCATION
              value: "/opt/microservice/certs/ca.crt"
            - name: NODE_EXTRA_CA_CERTS
              value: "/opt/microservice/certs/ca.crt"
          ports:
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - mountPath: "/opt/microservice/certs"
              name: confluent-ca
              readOnly: true
      volumes:
        - name: confluent-ca
          secret:
            secretName: confluent-ca
