name: ldap
image: osixia/openldap:1.5.0
tls:
  enabled: false
  fullchain: |-
  privkey: |-
  cacerts: |-

env:
  LDAP_ORGANISATION: "Test Inc."
  LDAP_DOMAIN: "test.com"
  LDAP_ADMIN_PASSWORD: "confluentrox"
  LDAP_CONFIG_PASSWORD: "confluentconfigrox"
  LDAP_READONLY_USER: "true"
  LDAP_READONLY_USER_USERNAME: "mds"
  LDAP_READONLY_USER_PASSWORD: "Developer!"
  LDAP_BASE_DN: "dc=test,dc=com"
  LDAP_TLS: "false"

# Adding integer before ldif name to allow sequence order.
ldifs:
  00_cf_connect.ldif: |-
    dn: cn=cf_connect,{{ LDAP_BASE_DN }}
    userPassword: y3ACj694swkZ
    description: Confluent Connect user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: cf_connect
  01_cf_controlcenter.ldif: |-
    dn: cn=cf_controlcenter,{{ LDAP_BASE_DN }}
    userPassword: PqKfw3HMDn4C
    description: Confluent Control Center user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: cf_controlcenter
  02_cf_kafka.ldif: |-
    dn: cn=cf_kafka,{{ LDAP_BASE_DN }}
    userPassword: uiGQ8i6gHvGt
    description: Confluent Kafka user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: cf_kafka
  03_cf_restproxy.ldif: |-
    dn: cn=cf_restproxy,{{ LDAP_BASE_DN }}
    userPassword: MZGknPvdL6ye
    description: Confluent REST Proxy user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: cf_restproxy
  04_cf_ksqldb.ldif: |-
    dn: cn=cf_ksqldb,{{ LDAP_BASE_DN }}
    userPassword: pF5Gw5fdYtPi
    description: Confluent ksqlDB user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: cf_ksqldb
  05_cf_schemaregistry.ldif: |-
    dn: cn=cf_schemaregistry,{{ LDAP_BASE_DN }}
    userPassword: KqUP8PyDd8ge
    description: Confluent Schema Registry user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: cf_schemaregistry
  06_cf_groupou.ldif: |-
    dn: ou=users,{{ LDAP_BASE_DN }}
    objectClass: organizationalUnit
    ou: Users

    dn: ou=groups,{{ LDAP_BASE_DN }}
    objectClass: organizationalUnit
    ou: Groups
