lsdmesp:
  clusterType: "kind"
  cpVersion: "7.8.0"
  cpOperatorVersion: "2.10.0"
  storageClass: standard
  defaultReplicationFactor: 3
  defaultMinInSyncReplicas: 2
  defaultNumPartitions: 6

  security:
    enabledDemo: true
    vault:
      enabled: false
      type: kv-v2
      mount: kvv2
      subPath: confluent
      auth:
        name: static-auth
        mount: demo-auth-mount
        kubernetes:
          role: role1
          serviceAccount: default
          audiences:
            - vault

  armyKnife:
    enabled: true
    image: lsdopen/kafka-army-knife:latest
    replicas: 1

  monitoring:
    enabled: false
    kafkaLagExporter:
      enabled: false
      image: lsdtrip/kafka-lag-exporter:latest
      replicas: 1

  confluentCli:
    enabled: true
    replicas: 0

  tls:
    ca:
      cert: ""
      key: ""
    mds:
      key: ""
      publicKey: ""

  ldap:
    # if `true`, then will be provisioned
    enabled: true
    readOnlyUser:
      username: "mds"
      password: ""
    image: osixia/openldap:1.5.0
    tls:
      enabled: false
      fullchain: |-
      privkey: |-
      cacerts: |-
    organisation: "Test Inc."
    domain: "test.com"
    admin_password: ""
    config_password: ""
    basedn: "dc=test,dc=com"
    env: {}

  confluent:
    kraftcontroller:
      # java memory sizes
      jvm:
        Xms: 384m
        Xmx: 384m
      # size of the pv needed
      dataVolumeCapacity: 1Gi
      # pod resource limits and request
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 20m
          memory: 512Mi
      # number of pod replicas
      replicas: 3

    kafka:
      # if `true`, then will be provisioned
      enabled: true
      # credential config
      username: cf_kafka
      password: ""
      # java memory sizes
      jvm:
        Xms: 1g
        Xmx: 1g
      # size of the pv needed
      dataVolumeCapacity: 20Gi
      # pod resource limits and request
      resources:
        limits:
          cpu: 1
          memory: 8Gi
        requests:
          cpu: 50m
          memory: 3Gi
      # number of pod replicas
      replicas: 3
      externalAccess: {}
      ingress:
        # -- Specifies whether an ingress for Kafka should be created
        enabled: false
        ingressClassName: "nginx"
        # -- Annotations for the Kafka ingress
        annotations: {}
        # -- Base domain configuration for the Kafka and brokers ingress ingress
        baseDomain: "example.com"
        # -- TLS host configuration will be dynamically built based on the base domain. You can change the secret name here.
        tls:
          secretName: kafka-tls

    kafkarestclass:
      # if `true`, then will be provisioned
      enabled: true

    schemaregistry:
      # if `true`, then will be provisioned
      enabled: true
      # credential config
      username: cf_schemaregistry
      password: ""
      # java memory sizes
      jvm:
        Xms: 384m
        Xmx: 384m
      # pod resource limits and request
      resources:
        limits:
          cpu: 200m
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 512Mi
      # number of pod replicas
      replicas: 1
      externalAccess: {}
      ingress:
        # -- Specifies whether an ingress for Schema Registry should be created
        enabled: false
        ingressClassName: "nginx"
        # -- Annotations for the Schema Registry ingress
        annotations: {}
        # -- Base domain configuration for the  Schema Registry ingress
        baseDomain: "example.com"
        # -- TLS host configuration will be dynamically built based on the base domain. You can change the secret name here.
        tls:
          secretName: schemaregistry-tls

    connect:
      # if `true`, then will be provisioned
      enabled: true
      # credential config
      username: cf_connect
      password: ""
      # java memory sizes
      jvm:
        Xms: 512m
        Xmx: 512m
      # pod resource limits and request
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 20m
          memory: 1Gi
      # number of pod replicas
      replicas: 1
      externalAccess: {}
      ingress:
        # -- Specifies whether an ingress for Connect should be created
        enabled: false
        ingressClassName: "nginx"
        # -- Annotations for the Connect ingress
        annotations: {}
        # -- Base domain configuration for the  Connect ingress
        baseDomain: "example.com"
        # -- TLS host configuration will be dynamically built based on the base domain. You can change the secret name here.
        tls:
          secretName: connect-tls

    ksqldb:
      # if `true`, then will be provisioned
      enabled: true
      # credential config
      username: cf_ksqldb
      password: ""
      # java memory sizes
      jvm:
        Xms: 512m
        Xmx: 512m
      # size of the pv needed
      dataVolumeCapacity: 5Gi
      # pod resource limits and request
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 1Gi
      # number of pod replicas
      replicas: 1
      externalAccess: {}
      ingress:
        # -- Specifies whether an ingress for KSQLDB should be created
        enabled: false
        ingressClassName: "nginx"
        # -- Annotations for the KSQLDB ingress
        annotations: {}
        # -- Base domain configuration for the KSQLDB ingress
        baseDomain: "example.com"
        # -- TLS host configuration will be dynamically built based on the base domain. You can change the secret name here.
        tls:
          secretName: ksqldb-tls

    kafkarestproxy:
      # if `true`, then will be provisioned
      enabled: true
      # credential config
      username: cf_restproxy
      password: ""
      # java memory sizes
      jvm:
        Xms: 384m
        Xmx: 384m
      # pod resource limits and request
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 512Mi
      # number of pod replicas
      replicas: 1

    controlcenter:
      # if `true`, then will be provisioned
      enabled: true
      # credential config
      username: cf_controlcenter
      password: ""
      # java memory sizes
      jvm:
        Xms: 2g
        Xmx: 2g
      # size of the pv needed
      dataVolumeCapacity: 10Gi
      # pod resource limits and request
      resources:
        limits:
          cpu: 2
          memory: 12Gi
        requests:
          cpu: 200m
          memory: 6Gi
      # number of pod replicas
      replicas: 1
      externalAccess: {}
      ingress:
        # -- Specifies whether an ingress for Control Center should be created
        enabled: false
        ingressClassName: "nginx"
        # -- Annotations for the Control Center ingress
        annotations: {}
        # -- Base domain configuration for the Control Center ingress
        baseDomain: "apps.mesp.lsdopen.io"
        # -- TLS host configuration will be dynamically built based on the base domain. You can change the secret name here.
        tls:
          secretName: controlcenter-tls

confluent-manager-for-apache-flink:
  cmf:
    authorization:
      mdsRestConfig:
        endpoint: https://kafka.lsdmesp.svc.cluster.local:8090
        authentication:
          type: basic
          config:
            confluent.metadata.basic.auth.user.info: "cf_connect:bk(2KW{LgFj3"
            confluent.metadata.bootstrap.server.urls: https://kafka.lsdmesp.svc.cluster.local:8090
            confluent.metadata.http.auth.credentials.provider: BASIC
            confluent.metadata.ssl.truststore.location: /mnt/sslcerts/truststore.jks
            confluent.metadata.ssl.truststore.password: mystorepassword
    ssl:
      keystore: /opt/keystore/keystore.p12
      keystore-password: 112233
      trust-store: /mnt/sslcerts/truststore.jks
      trust-store-password: mystorepassword
      client-auth: need
    authentication:
      type: mtls
    k8s: #This configuration is only required if you did not setup FKO and CMF can reach FKO
      enabled: true
  mountedVolumes:
    volumeMounts:
      - name: truststore
        mountPath: /mnt/sslcerts
      - name: keystore
        mountPath: /opt/keystore
    volumes:
      - name: truststore
        secret:
          secretName: kafka-generated-jks
      - name: keystore
        configMap:
          name: cmf-keystore

confluent-for-kubernetes:
  name: confluent-operator
  licenseKey: ""
  license:
    secretRef: ""
    directoryPathInContainer: ""
  managedCerts:
    enabled: false
    caCertificate:
      secretRef: ""
      directoryPathInContainer: ""
    certDurationInDays: 60
    renewBeforeInDays: 30
    sans: ""
  imagePullSecretRef:  confluent-registry
  image:
    registry: docker.io
    repository: confluentinc/confluent-operator
    pullPolicy: IfNotPresent
    tag: "0.1145.6"
  priorityClassName: ""
  replicas: 1
  namespaced: true
  namespaceList: []
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  terminationGracePeriodSeconds: 30
  debug: false
  fipsmode: false
  numDay2Worker: ""
  enableCMFDay2Ops: true
  affinity: {}
  tolerations: []
  podSecurity:
    enabled: true
    securityContext:
      fsGroup: 1001
      runAsUser: 1001
      runAsNonRoot: true
  containerSecurity:
    enabled: false
    securityContext: {}
  serviceAccount:
    create: true
    name: ""
  rbac: true
  clusterRole:
    openshift: false
  telemetry:
    operator:
      enabled: false
    enabled: false
    proxy:
      enabled: false
      credentialRequired: false
    secretRef: ""
    directoryPathInContainer: ""
  kRaftEnabled: true
  webhooks:
    enabled: false
    port: 8443
    tls:
      secretRef: ""
      directoryPathInContainer: ""
  pod:
    annotations:
      prometheus.io/path: "/metrics"
      prometheus.io/port: "7778"
      prometheus.io/scrape: "true"
    labels: {}
  licenseSecretRef: ""
  mountedVolumes:
    volumes: []
    volumeMounts: []
