{{- if .Values.restSecurity.basic.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: lsdmesp-passwords
stringData:
  passwords.txt: |-
    bob: bob-secret,developer
    client: client-secret,developer
  connect_passwords.txt: |-
    bob: bob-secret
    client: client-secret
{{- end }}
