{{- if .Values.restSecurity.basic.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: lsdmesp-passwords
stringData:
  passwords.txt: |-
    {{ .Values.restSecurity.basic.apiUser }}: {{ .Values.restSecurity.basic.apiPassword }},developer
    {{- range $key, $value := .Values.restSecurity.basic.clientUsers }}
    {{ $key }}: {{ $value }},developer
    {{- end }}
  connect_passwords.txt: |-
    {{ .Values.restSecurity.basic.apiUser }}: {{ .Values.restSecurity.basic.apiPassword }}
    {{- range $key, $value := .Values.restSecurity.basic.clientUsers }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}
