{
 "title": "Debezium Connectors",
 "description": "Monitoring Dashboard for Debezium connector",
 "tags": [
  "mysql",
  "debezium",
  "postgres",
  "mongodb",
  "sqlserver"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Streaming Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "General Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "\n# Debezium Connector Metrics\n\nThe Debezium connectors has three metric types:\n\n* snapshot metrics\n\n* binlog metrics (MySql)\n\n* schema history metrics (MySql and SQLServer)\n\nFor more detailed informarion about the metrics please visit the Debezium documentation page\n\n[Click here to visit](https://debezium.io/documentation/reference/stable/operations/monitoring.html)\n\n\n\n"
   }
  },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_connected{context=\"streaming\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Binlog Position (MySql only)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_binlogposition{context=\"streaming\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "GTID Enabled (MySql only)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_isgtidmodeenabled{context=\"streaming\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Committed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_numberofcommittedtransactions{context=\"streaming\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "RolledBack Transactions (MySql only)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_numberofrolledbacktransactions{context=\"streaming\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Not WellFormed Transactions (MySql only)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_numberofnotwellformedtransactions{context=\"streaming\",name=\"mesp\"}\r\n"
    }
   ]
  },
  {
   "title": "Total Number Of Events Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"streaming\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Skipped Events",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_numberofskippedevents{context=\"streaming\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Events Filtered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_numberofeventsfiltered{context=\"streaming\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Seconds Since Last Event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "debezium_metrics_millisecondssincelastevent{context=\"streaming\",name=\"mesp\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_queuetotalcapacity{context=\"streaming\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_queueremainingcapacity{context=\"streaming\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Seconds Behind Master (MySql only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "debezium_metrics_secondsbehindmaster{context=\"streaming\",name=\"mesp\"}",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "MilliSeconds Behind Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "debezium_metrics_millisecondsbehindsource{context=\"streaming\",name=\"mesp\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Disconnects (MySql and Mongo only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_numberofdisconnects{context=\"streaming\",name=\"mesp\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Large Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_numberoflargetransactions{context=\"streaming\",name=\"mesp\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  { "title": "Snapshot Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Table count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_totaltablecount{context=\"snapshot\",name=\"mesp\"}"
    }
   ]
  },
  {
   "title": "Remaining Tables",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_remainingtablecount{context=\"snapshot\",name=\"mesp\"}"
    }
   ]
  },
  {
   "title": "Holding GlobalLock",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_holdinggloballock{context=\"snapshot\",name=\"mesp\"}"
    }
   ]
  },
  {
   "title": "Snapshot Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotrunning{context=\"snapshot\",name=\"mesp\"}"
    }
   ]
  },
  {
   "title": "Snapshot Aborted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotaborted{context=\"snapshot\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Snapshot Completed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotcompleted{context=\"snapshot\",name=\"mesp\"}"
    }
   ]
  },
  {
   "title": "Snapshot Duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_snapshotdurationinseconds{context=\"snapshot\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Events Filtered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_numberofeventsfiltered{context=\"snapshot\",name=\"mesp\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Time Since Last Event",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_millisecondssincelastevent{context=\"snapshot\",name=\"mesp\"}\r\n"
    }
   ]
  },
  {
   "title": "Queue Total Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_queuetotalcapacity{context=\"snapshot\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_queueremainingcapacity{context=\"snapshot\",name=\"mesp\"}\t\r\n"
    }
   ]
  },
  {
   "title": "Erroneous Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_numberoferroneousevents{context=\"snapshot\",name=\"mesp\"}\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Events Seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"snapshot\",name=\"mesp\"}\t\r\n",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  { "title": "Schema History Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Schema Changes info",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 55 },
   "options": {
    "content": "\n# Schema Changes Metrics\n\nFor detailed explanation for all the schema changes metrics: [Visit Debezium documentation](https://debezium.io/documentation/reference/1.0/assemblies/cdc-mysql-connector/as_deploy-the-mysql-connector.html#mysql-connector-schema-history-metrics)\n\n\n\n\n"
   }
  },
  {
   "title": "Recovery StartTime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_recoverystarttime{context=\"schema-history\",name=\"mesp\"}"
    }
   ]
  },
  {
   "title": "Since Last Applied Change",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_millisecondssincelastappliedchange{context=\"schema-history\",name=\"mesp\"}\t\r"
    }
   ]
  },
  {
   "title": "Since Last RecoveredChange",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_millisecondssincelastrecoveredchange{context=\"schema-history\",name=\"mesp\"}\t\r"
    }
   ]
  },
  {
   "title": "Changes Recovered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_changesrecovered{context=\"schema-history\",name=\"mesp\"}\t\r",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Changes Applied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "debezium_metrics_changesapplied{context=\"schema-history\",name=\"mesp\"}\t\r",
     "legendFormat": "{{name}} ({{plugin}})"
    }
   ]
  }
 ]
}