apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: generic-consumer
  labels:
    strimzi.io/cluster: {{ .Values.lsdmesp.strimzi.clusterName }}
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - Describe
          - Read
        host: "*"
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - Read
        host: "*"