{{- if .Values.lsdmesp.armyKnife.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-army-knife-env
  namespace: lsdmesp
data:
  environment: |
    export BOOTSTRAP_SERVERS=lsdmesp-kafka-bootstrap:9092
    export BOOTSTRAP_SERVERS_EXT={{ .Values.lsdmesp.strimzi.kafka.bootstrap }}
    export CONNECT_HOST=http://lsdmesp-connect-api:8083
    export SCHEMA_REGISTRY=http://lsdmesp-cp-schema-registry:8081
    export PATH=$PATH:/root/scripts/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-army-knife
  namespace: lsdmesp
  labels:
    app: kafka-army-knife
spec:
  replicas: {{ .Values.lsdmesp.armyKnife.replicas }}
  selector:
    matchLabels:
      app: kafka-army-knife
  template:
    metadata:
      labels:
        app: kafka-army-knife
    spec:
      containers:
      - env:
        - name: BOOTSTRAP_SERVERS
          value: lsdmesp-kafka-bootstrap:9092
        - name: BOOTSTRAP_SERVERS_EXT
          value: {{ .Values.lsdmesp.strimzi.kafka.bootstrap }}
        - name: CONNECT_HOST
          value: http://lsdmesp-connect-api:8083
        - name: SCHEMA_REGISTRY
          value: http://lsdmesp-cp-schema-registry:8081
        image: {{ .Values.lsdmesp.armyKnife.image }}
        command:
          - sleep
          - "360000"
        imagePullPolicy: IfNotPresent
        name: kafka-army-knife
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /root/.kafka-army-knife
          name: kafka-army-knife-env
      volumes:
      - configMap:
          defaultMode: 420
          name: kafka-army-knife-env
        name: kafka-army-knife-env
{{- end -}}
