---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-army-knife-env
  namespace: lsdmesp
data:
  environment: |
    export BOOTSTRAP_SERVERS=lsdmesp-kafka-bootstrap:9092
    export BOOTSTRAP_SERVERS_EXT={{ .Values.lsdmesp.strimzi.kafka.bootstrap }}
    export CONNECT_HOST=http://lsdmesp-connect-api:8083
    export SCHEMA_REGISTRY=http://lsdmesp-cp-schema-registry:8081
    export PATH=$PATH:/root/scripts/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: kafka-army-knife
    meta.helm.sh/release-namespace: lsdmesp
  labels:
    app.kubernetes.io/instance: kafka-army-knife
    app.kubernetes.io/name: kafka-army-knife
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: kafka-army-knife-0.2.0
  name: kafka-army-knife
  namespace: lsdmesp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: kafka-army-knife
      app.kubernetes.io/name: kafka-army-knife
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kafka-army-knife
        app.kubernetes.io/name: kafka-army-knife
    spec:
      containers:
      - env:
        - name: BOOTSTRAP_SERVERS
          value: lsdmesp-kafka-bootstrap:9092
        - name: BOOTSTRAP_SERVERS_EXT
          value: {{ .Values.lsdmesp.strimzi.kafka.bootstrap }}
        - name: CONNECT_HOST
          value: http://lsdmesp-connect-api:8083
        - name: SCHEMA_REGISTRY
          value: http://lsdmesp-cp-schema-registry:8081
        image: lsdopen/kafka-army-knife:latest
        imagePullPolicy: IfNotPresent
        name: kafka-army-knife
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.kafka-army-knife
          name: kafka-army-knife-env
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: kafka-army-knife-env
        name: kafka-army-knife-env
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-army-knife
  namespace: lsdmesp
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: ssh
    nodePort: 32731
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app.kubernetes.io/instance: kafka-army-knife
    app.kubernetes.io/name: kafka-army-knife
  sessionAffinity: None
  type: NodePort
