{{ if .Values.lsdmesp.kafka.kafkaguis.auth.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lsdmesp.kafka.kafkaguis.auth.secretName }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: "Opaque"
data:
  auth: {{ htpasswd .Values.lsdmesp.kafka.kafkaguis.auth.username .Values.lsdmesp.kafka.kafkaguis.auth.password | b64enc | quote }}
{{ end }}
