# Kafka-UI Ingress
{{- if or (eq .Values.lsdmesp.clusterType "gke") (eq .Values.lsdmesp.clusterType "rancher") -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    {{ if .Values.lsdmesp.kafka.kafkaguis.auth.enabled }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.lsdmesp.kafka.kafkaguis.auth.secretName }}
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    {{ end }}
  labels:
    app: kafka-ui
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: lsdmesp-kafka-ui
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.lsdmesp.kafka.kafkaui.ingress.url }}
    http:
      paths:
      - backend:
          service:
            name: lsdmesp-kafka-ui
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.lsdmesp.kafka.kafkaui.ingress.url }}
---
{{- end }}
