---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: udfs-lsdmesp-cp-ksql-server
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
---
