# Kafka KSQL Ingress and NodePort
{{- if or (eq .Values.lsdmesp.clusterType "gke") (eq .Values.lsdmesp.clusterType "rancher") -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: cp-ksql-server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: lsdmesp-cp-ksql-server-external
spec:
  rules:
  - host: {{ .Values.lsdmesp.confluent.ksqldb.ingress.url }}
    http:
      paths:
      - backend:
          serviceName: lsdmesp-cp-ksql-server
          servicePort: 8088
        path: /
        pathType: ImplementationSpecific
---
{{- end }}
