# Kafka Schema Registry Ingress and NodePort
{{- if or (eq .Values.lsdmesp.clusterType "gke") (eq .Values.lsdmesp.clusterType "rancher") -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: cp-ksql-server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: lsdmesp-cp-schema-registry-external
spec:
  rules:
  - host: {{ .Values.lsdmesp.confluent.schemaRegistry.ingress.url }}
    http:
      paths:
      - backend:
          serviceName: lsdmesp-cp-schema-registry
          servicePort: 8081
        path: /
        pathType: ImplementationSpecific
---
{{- end }}
