# Connect-UI Ingress
{{- if or (eq .Values.lsdmesp.clusterType "gke") (eq .Values.lsdmesp.clusterType "rancher") -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: kafka-connect-ui
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: lsdmesp-connect-ui
spec:
  rules:
  - host: {{ .Values.lsdmesp.kafka.connectui.ingress.url }}
    http:
      paths:
      - backend:
          serviceName: lsdmesp-kafka-connect-ui
          servicePort: 8000
        path: /
        pathType: ImplementationSpecific
---
{{- end }}
