# Default values for lsdmesp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
lsdmesp:
  clusterType: "kind"
  cpVersion: "7.6.1"
  storageClass: standard
  defaultReplicationFactor: 3
  defaultMinInSyncReplicas: 2
  defaultNumPartitions: 6
  confluentKsqldbURL: &anchorconfluentKsqldbURL "ksqldb.apps.mesp.lsdopen.io"
  confluentSchemaRegistryURL: &anchorconfluentSchemaRegistryURL "schema-registry.apps.mesp.lsdopen.io"
  strimziConnectURL: &anchorstrimziConnectURL "connect.apps.mesp.lsdopen.io"
  kafkaAllUIUsername: &anchorkafkaAllUIUsername "kafka"
  kafkaAllUIPassword: &anchorkafkaAllUIPassword "secretpassword"

  prometheus:
    # Requires podmonitors.monitoring.coreos.com CRD
    enableMetrics: true

  internalSecurity:
    enabled: true

  strimzi:
    clusterName: lsdmesp
    version: 3.6.1

    kraftcontroller:
      # java memory sizes
      jvm:
        Xms: 384m
        Xmx: 384m
      # size of the pv needed
      dataVolumeCapacity: 1Gi
      # pod resource limits and request
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 20m
          memory: 512Mi
      # number of pod replicas
      replicas: 3

    kafka:
      bootstrap: "bootstrap.mesp.lsdopen.io:32100"
      externalDomain: "mesp.lsdopen.io"
      # java memory sizes
      jvm:
        Xms: 1g
        Xmx: 1g
      # size of the pv needed
      dataVolumeCapacity: 20Gi
      # pod resource limits and request
      resources:
        limits:
          cpu: 1
          memory: 8Gi
        requests:
          cpu: 50m
          memory: 3Gi
      # number of pod replicas
      replicas: 3

    topicOperator:
      # pod resource limits and request
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 10Mi

    userOperator:
      # pod resource limits and request
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 10m
          memory: 10Mi

    connect:
      ingress:
        url: *anchorstrimziConnectURL

  kafka:
    kafkaguis:
      auth:
        enabled: true
        secretName: "lsdmesp-guis-basic-auth"
        username: *anchorkafkaAllUIUsername
        password: *anchorkafkaAllUIPassword
    kafkaui:
      enabled: true
      ingress:
        url: "kafka-ui.apps.mesp.lsdopen.io"

  confluent:
    ksqldb:
      ingress:
        url: *anchorconfluentKsqldbURL
    schemaRegistry:
      ingress:
        url: *anchorconfluentSchemaRegistryURL

  armyKnife:
    enabled: true
    image: lsdopen/kafka-army-knife:latest
    replicas: 1

cp-helm:
  # REST API security
  restSecurity:
    basic:
      enabled: true

  ## ------------------------------------------------------
  ## Connect
  ## ------------------------------------------------------
  cp-kafka-connect:
    enabled: true
    internalSecurity:
      enabled: true
    restSecurity:
      tls:
        enabled: true
      basic:
        enabled: true
    replicaCount: 1
    image: lsdtrip/cp-kafka-connect
    imageTag: "7.6.1"
    servicePort: 8083
    configurationOverrides:
      "plugin.path": "/usr/share/java,/usr/share/confluent-hub-components"
      "key.converter": "io.confluent.connect.avro.AvroConverter"
      "value.converter": "io.confluent.connect.avro.AvroConverter"
      "key.converter.schemas.enable": "false"
      "value.converter.schemas.enable": "false"
      "internal.key.converter": "org.apache.kafka.connect.json.JsonConverter"
      "internal.value.converter": "org.apache.kafka.connect.json.JsonConverter"
      "config.storage.replication.factor": "3"
      "offset.storage.replication.factor": "3"
      "status.storage.replication.factor": "3"
    heapOptions: "-Xms512M -Xmx512M"
    kafkaConnectOpts: "-Djava.security.auth.login.config=/opt/kafka/jaas-config/jaas_connect.conf"
    kafka:
      bootstrapServers: "lsdmesp-kafka-bootstrap:9092"
    cp-schema-registry:
      url: "https://lsdmesp-cp-schema-registry:8081"
    resources:
      limits:
        memory: 2Gi
        cpu: 1
      requests:
        memory: 768Mi
        cpu: 10m
  ## ------------------------------------------------------
  ## Schema Registry
  ## ------------------------------------------------------
  cp-schema-registry:
    enabled: true
    internalSecurity:
      enabled: true
    restSecurity:
      tls:
        enabled: true
      basic:
        enabled: true
    replicaCount: 1
    image: confluentinc/cp-schema-registry
    imageTag: "7.6.1"
    heapOptions: "-Xms512m -Xmx512m"
    schemaRegistryOpts: "-Djava.security.auth.login.config=/opt/kafka/jaas-config/jaas_config.conf"
    kafka:
      bootstrapServers: "lsdmesp-kafka-bootstrap:9092"
    resources:
      limits:
        memory: 2Gi
        cpu: 1
      requests:
        memory: 768Mi
        cpu: 10m
  ## ------------------------------------------------------
  ## REST Proxy
  ## ------------------------------------------------------
  cp-kafka-rest:
    enabled: true
    internalSecurity:
      enabled: true
    restSecurity:
      tls:
        enabled: true
      basic:
        enabled: true
    replicaCount: 1
    image: confluentinc/cp-kafka-rest
    imageTag: "7.6.1"
    heapOptions: "-Xms512m -Xmx512m"
    kafkaRestOpts: "-Djava.security.auth.login.config=/opt/kafka/jaas-config/jaas_config.conf"
    cp-kafka:
      bootstrapServers: "lsdmesp-kafka-bootstrap:9092"
    cp-schema-registry:
      url: "https://lsdmesp-cp-schema-registry:8081"
    resources:
      limits:
        memory: 2Gi
        cpu: 500m
      requests:
        memory: 768Mi
        cpu: 10m
  ## ------------------------------------------------------
  ## KSQL Server
  ## ------------------------------------------------------
  cp-ksql-server:
    enabled: true
    internalSecurity:
      enabled: true
    restSecurity:
      tls:
        enabled: true
      basic:
        enabled: true
    replicaCount: 1
    image: confluentinc/cp-ksqldb-server
    imageTag: "7.6.1"
    heapOptions: "-Xms512M -Xmx1g"
    ksqlOpts: "-Djava.security.auth.login.config=/opt/kafka/jaas-config/jaas_config.conf"
    overrideServiceId: lsdmesp-ksql-server
    ksql:
      headless: false
    configurationOverrides:
      ksql.connect.url: "http://lsdmesp-connect-api:8083"
      ksql.extension.dir: /opt/ksqldb-udfs
      ksql.internal.topic.replicas: 3
      log4j.root.loglevel: WARN
      confluent.support.metrics.enable: false
      ksql.streams.num.stream.threads: 2
      ksql.streams.consumer.heartbeat.interval.ms: 10000
      ksql.streams.consumer.session.timeout.ms: 180000
      ksql.streams.consumer.max.poll.interval.ms: "86400000"
      ksql.streams.consumer.request.timeout.ms: 60000
    kafka:
      bootstrapServers: "lsdmesp-kafka-bootstrap:9092"
    cp-schema-registry:
      url: "https://lsdmesp-cp-schema-registry:8081"
    resources:
      requests:
        cpu: 10m
        memory: 2Gi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cp-ksql-server
              - key: release
                operator: In
                values:
                - lsdmesp
            topologyKey: kubernetes.io/hostname
          weight: 100

strimzi-kafka-operator:
  replicas: 1
  watchNamespaces: []
  watchAnyNamespace: false
  defaultImageRegistry: quay.io
  defaultImageRepository: strimzi
  defaultImageTag: 0.41.0
  image:
    imagePullPolicy: IfNotPresent
    registry: ""
    repository: ""
    name: operator
    tag: ""
    # imagePullSecrets:
    #   - name: secretname
  logVolume: co-config-volume
  logConfigMap: strimzi-cluster-operator
  logConfiguration: ""
  logLevel: ${env:STRIMZI_LOG_LEVEL:-INFO}
  fullReconciliationIntervalMs: 120000
  operationTimeoutMs: 300000
  kubernetesServiceDnsDomain: cluster.local
  featureGates: ""
  tmpDirSizeLimit: 1Mi
  extraEnvs: []
  tolerations: []
  affinity: {}
  annotations: {}
  labels: {}
  nodeSelector: {}
  priorityClassName: ""
  podSecurityContext: {}
  securityContext: {}
  rbac:
    create: yes
  serviceAccountCreate: yes
  serviceAccount: strimzi-cluster-operator
  leaderElection:
    enable: true
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    maxUnavailable:
  dashboards:
    enabled: false
    namespace: ~
    label: grafana_dashboard # this is the default value from the grafana chart
    labelValue: "1" # this is the default value from the grafana chart
    annotations: {}
    extraLabels: {}
  kafka:
    image:
      registry: ""
      repository: ""
      name: kafka
      tagPrefix: ""
  kafkaConnect:
    image:
      registry: "docker.io"
      repository: "lsdtrip"
      name: kafka-connect
      tagPrefix: ""
  topicOperator:
    image:
      registry: ""
      repository: ""
      name: operator
      tag: ""
  userOperator:
    image:
      registry:
      repository:
      name: operator
      tag: ""
  kafkaInit:
    image:
      registry: ""
      repository: ""
      name: operator
      tag: ""
  kafkaMirrorMaker:
    image:
      registry: ""
      repository: ""
      name: kafka
      tagPrefix: ""
  kafkaBridge:
    image:
      registry: ""
      repository:
      name: kafka-bridge
      tag: 0.28.0
  kafkaExporter:
    image:
      registry: ""
      repository: ""
      name: kafka
      tagPrefix: ""
  kafkaMirrorMaker2:
    image:
      registry: ""
      repository: ""
      name: kafka
      tagPrefix: ""
  cruiseControl:
    image:
      registry: ""
      repository: ""
      name: kafka
      tagPrefix: ""
  kanikoExecutor:
    image:
      registry: ""
      repository: ""
      name: kaniko-executor
      tag: ""
  mavenBuilder:
    image:
      registry: ""
      repository: ""
      name: maven-builder
      tag: ""
  resources:
    limits:
      memory: 384Mi
      cpu: 1000m
    requests:
      memory: 384Mi
      cpu: 10m
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 30
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 30
  createGlobalResources: true
  createAggregateRoles: false
  labelsExclusionPattern: ""
  generateNetworkPolicy: true
  connectBuildTimeoutMs: 300000

kafka-ui:
  env:
    - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
      value: "SASL_SSL"
    - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
      value: "SCRAM-SHA-512"
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: "lsdmesp-kafka-bootstrap:9092"
    - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
      valueFrom:
        secretKeyRef:
          name: lsdmesp
          key: sasl.jaas.config
    - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION
      value: "/opt/kafka/certs-cluster-ca/ca.p12"
    - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: lsdmesp-cluster-ca-cert
          key: ca.password
    - name: KAFKA_CLUSTERS_0_SSL_TRUSTSTORELOCATION
      value: "/opt/kafka/basicauth/truststore.p12"
    - name: KAFKA_CLUSTERS_0_SSL_TRUSTSTOREPASSWORD
      valueFrom:
        secretKeyRef:
          name: lsdmesp-tls
          key: password
    - name: KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
      value: ""
    - name: KAFKA_CLUSTERS_0_KSQLDBSERVER
      value: "https://lsdmesp-cp-ksql-server:8088"
    - name: KAFKA_CLUSTERS_0_KSQLDBSERVERAUTH_USERNAME
      valueFrom:
        secretKeyRef:
          name: lsdmesp-api
          key: user
    - name: KAFKA_CLUSTERS_0_KSQLDBSERVERAUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: lsdmesp-api
          key: password
    - name: KAFKA_CLUSTERS_0_NAME
      value: "lsdmesp"
    - name: KAFKA_CLUSTERS_0_READONLY
      value: "false"
    - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
      value: "https://lsdmesp-cp-schema-registry:8081"
    - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRYAUTH_USERNAME
      valueFrom:
        secretKeyRef:
          name: lsdmesp-api
          key: user
    - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRYAUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: lsdmesp-api
          key: password
    - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
      value: "connect-1"
    - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
      value: "https://lsdmesp-cp-kafka-connect:8083"
    - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_USERNAME
      valueFrom:
        secretKeyRef:
          name: lsdmesp-api
          key: user
    - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_PASSWORD
      valueFrom:
        secretKeyRef:
          name: lsdmesp-api
          key: password
  volumeMounts:
    - name: lsdmesp
      mountPath: /opt/kafka/certs-lsdmesp
    - name: lsdmesp-cluster-ca-cert
      mountPath: /opt/kafka/certs-cluster-ca
    - name: lsdmesp-tls
      mountPath: /opt/kafka/basicauth
  volumes:
    - name: lsdmesp
      secret:
        defaultMode: 292
        secretName: lsdmesp
    - name: lsdmesp-cluster-ca-cert
      secret:
        defaultMode: 292
        secretName: lsdmesp-cluster-ca-cert
    - name: lsdmesp-tls
      secret:
        defaultMode: 292
        secretName: lsdmesp-tls
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: lsdmesp-guis-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    enabled: true
    ingressClassName: nginx
    path: /
    host: "kafka-ui.apps.mesp.lsdopen.io"
    tls:
      enabled: true
