apiVersion: v1
data:
  basic.txt: dXNlcm5hbWU9Y2Zfc2NoZW1hcmVnaXN0cnkKcGFzc3dvcmQ9S3FVUDhQeURkOGdl
  bearer.txt: dXNlcm5hbWU9Y2Zfc2NoZW1hcmVnaXN0cnkKcGFzc3dvcmQ9S3FVUDhQeURkOGdl
kind: Secret
metadata:
  creationTimestamp: null
  name: schemaregistry-login
