{{- $kafkarestclass := .Values.lsdmesp.confluent.kafkarestclass -}}
{{- if $kafkarestclass.enabled -}}
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: default
spec:
  kafkaRest:
    authentication:
      bearer:
        secretRef: kafkarestclass-login
      type: bearer
{{- end -}}
