{{- $schemaregistry := .Values.lsdmesp.confluent.schemaregistry -}}
{{- if $schemaregistry.enabled -}}
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
spec:
  authorization:
    type: rbac
  configOverrides:
    jvm:
      - -Xms384m
      - -Xmx384m
  dependencies:
    kafka:
      authentication:
        type: mtls
      bootstrapEndpoint: kafka.lsdmesp-confluent.svc.cluster.local:9071
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.lsdmesp-confluent.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: schemaregistry-login
      tls:
        enabled: true
  image:
    application: confluentinc/cp-schema-registry:{{ .Values.lsdmesp.cpVersion }}
    init: confluentinc/confluent-init-container:{{ .Values.lsdmesp.cpOperatorVersion }}
  internalTopicReplicatorFactor: 3
  oneReplicaPerNode: true
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      {{- toYaml $schemaregistry.resources | nindent 6 }}
  replicas: 1
  tls:
    autoGeneratedCerts: true
{{- end -}}
