apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
spec:
  build:
    onDemand:
      plugins:
        confluentHub:
        - name: kafka-connect-datagen
          owner: confluentinc
          version: 0.6.3
        - name: kafka-connect-jdbc
          owner: confluentinc
          version: 10.7.4
        - name: kafka-connect-http
          owner: confluentinc
          version: 1.7.5
        - name: kafka-connect-elasticsearch
          owner: confluentinc
          version: 14.0.12
        - name: kafka-connect-s3-source
          owner: confluentinc
          version: 2.5.10
        - name: kafka-connect-s3
          owner: confluentinc
          version: 10.5.7
        - name: debezium-connector-mysql
          owner: debezium
          version: 2.2.1
        - name: kafka-connect-elasticsearch-source
          owner: dariobalinzo
          version: 1.5.5
        locationType: confluentHub
    type: onDemand
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.lsdmesp-confluent.svc.cluster.local:9071
      authentication:
        type: mtls      
      tls:
        enabled: true
    schemaRegistry:
      authentication:
        type: mtls
      tls:
        enabled: true
      url: https://schemaregistry.lsdmesp-confluent.svc.cluster.local:8081
  tls:
    autoGeneratedCerts: true      
  image:
    application: confluentinc/cp-server-connect:7.5.3
    init: confluentinc/confluent-init-container:2.7.3
  oneReplicaPerNode: true
  authentication:
    type: mtls  
  podTemplate:
    podSecurityContext: {}
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 500Mi
  replicas: 1
