{{- $ksqldb := .Values.lsdmesp.confluent.ksqldb -}}
{{- if $ksqldb.enabled -}}
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
spec:
  authorization:
    type: rbac
  configOverrides:
    jvm:
      - -Xms512m
      - -Xmx512m
    server:
      - ksql.internal.topic.replicas=3
      - ksql.logging.processing.topic.replication.factor=3
  dataVolumeCapacity: {{ $ksqldb.dataVolumeCapacity }}
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.{{ .Release.Namespace }}.svc.cluster.local:9071
      authentication:
        type: mtls      
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.{{ .Release.Namespace }}.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: ksqldb-login
      tls:
        enabled: true
    schemaRegistry:
      tls:
        enabled: true
      url: https://schemaregistry.{{ .Release.Namespace }}.svc.cluster.local:8081
  image:
    application: confluentinc/cp-ksqldb-server:{{ .Values.lsdmesp.cpVersion }}
    init: confluentinc/confluent-init-container:{{ .Values.lsdmesp.cpOperatorVersion }}
  internalTopicReplicationFactor: 3
  oneReplicaPerNode: true
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      {{- toYaml $ksqldb.resources | nindent 6 }}
  replicas: {{ $ksqldb.replicas }}
  storageClass:
    name: {{ .Values.lsdmesp.storageClass }}
  tls:
    autoGeneratedCerts: true
{{- end -}}
