apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
spec:
  authorization:
    type: rbac
  configOverrides:
    jvm:
      - -Xms384m
      - -Xmx384m
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.lsdmesp-confluent.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    mds:
      endpoint: https://kafka.lsdmesp-confluent.svc.cluster.local:8090
      tokenKeyPair:
        secretRef: mds-token
      authentication:
        type: bearer
        bearer:
          secretRef: kafkarestproxy-login
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.lsdmesp-confluent.svc.cluster.local:8081
      tls:
        enabled: true
  image:
    application: confluentinc/cp-kafka-rest:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  oneReplicaPerNode: true
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 512Mi  
  replicas: 1
  tls:
    autoGeneratedCerts: true
