## @param fullnameOverride String to fully override sealed-secrets.fullname
##
fullnameOverride: "sealed-secrets-controller"
## @param namespace Namespace where to deploy the Sealed Secrets controller
##
namespace: "kube-system"
