{
 "title": "Confluent Rest Proxy",
 "description": "Monitor Confluent Rest Proxy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "query_result(kafka_cruisecontrol_loadmonitor_valid_windows_value)"
   },
   {
    "name": "strimzi_cluster_name",
    "label": "Cluster Name",
    "query": "query_result(kafka_cruisecontrol_loadmonitor_valid_windows_value{namespace=\"$kubernetes_namespace\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections Active",
   "type": "stat",
   "description": "Total number of active TCP connections",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_rest_jetty_metrics_connections_active{job=\"lsdmesp-cp-kafka-rest\",  namespace=\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "Busy Threads Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_rest_jetty_metrics_busy_thread_count{job=\"lsdmesp-cp-kafka-rest\",  namespace=\"$kubernetes_namespace\"})"
    }
   ]
  },
  {
   "title": "Threads Pool Usage %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_rest_jetty_metrics_thread_pool_usage{job=\"lsdmesp-cp-kafka-rest\",  namespace=\"$kubernetes_namespace\"}"
    }
   ]
  },
  {
   "title": "Request Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_rest_jetty_metrics_request_queue_size{job=\"lsdmesp-cp-kafka-rest\",  namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections Opened Rate per sec",
   "type": "timeseries",
   "description": "The average rate per second of opened TCP connections",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_rest_jetty_metrics_connections_opened_rate{job=\"lsdmesp-cp-kafka-rest\",  namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections Closed Rate per sec",
   "type": "timeseries",
   "description": "The average rate per second of closed TCP connections",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_rest_jetty_metrics_connections_closed_rate{job=\"lsdmesp-cp-kafka-rest\",  namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connections Accepted Rate per sec",
   "type": "timeseries",
   "description": "The average rate per second of accepted TCP connections",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_rest_jetty_metrics_connections_accepted_rate{job=\"lsdmesp-cp-kafka-rest\",  namespace=\"$kubernetes_namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"lsdmesp-cp-kafka-rest\",namespace=\"$kubernetes_namespace\"}[5m])",
     "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"lsdmesp-cp-kafka-rest\",namespace=\"$kubernetes_namespace\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=\"lsdmesp-cp-kafka-rest\",namespace=\"$kubernetes_namespace\",area=\"heap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"lsdmesp-cp-kafka-rest\",namespace=\"$kubernetes_namespace\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}