apiVersion: v1
kind: Secret
metadata:
  name: demo-notification-service-client-properties
stringData:
  client.properties: |-
    security.protocol=SASL_SSL
    sasl.mechanism=PLAIN
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="peter" password="peter-secret";
    ssl.truststore.location=/home/kafka/lsdmesp.truststore.jks
    ssl.truststore.password=112233
    basic.auth.credentials.source=USER_INFO
    basic.auth.user.info=peter:peter-secret
    schema.registry.ssl.truststore.location=/home/kafka/lsdmesp.truststore.jks
    schema.registry.ssl.truststore.password=112233
  mail.properties: |-
    smtp.host=smtp.sendgrid.net
    smtp.port=587
    smtp.username=apikey
    smtp.password=<apipassword>
    smtp.from.email=rainer@lsdopen.io
    smtp.to.email=rainer@lsdopen.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-notification-service
  labels:
    app: demo-notification-service
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo-notification-service
  template:
    metadata:
      labels:
        app: demo-notification-service
    spec:
      containers:
        - image: lsdtrip/demo-notification-service:latest
          command:
            - java
            - -jar
            - app.jar
            - --bootstrap-servers
            - kafka.lsdmesp-confluent.svc.cluster.local:9092
            - --schema-registry-url
            - https://schemaregistry.lsdmesp-confluent.svc.cluster.local:8081
            - --source-topic
            - jdbc_bank_transactions_enriched
            - --command-config
            - /opt/etc/client.properties
            - --mail-config
            - /opt/etc/mail.properties
          imagePullPolicy: Always
          name: demo-notification-service
          lifecycle:
            postStart:
              exec:
                command: [ 'sh', '-c', "keytool -keystore /home/kafka/lsdmesp.truststore.jks -alias CARoot -importcert -file /opt/certs/ca.pem -storepass 112233 -noprompt" ]
          volumeMounts:
            - mountPath: /opt/etc
              name: demo-notification-service-client-properties
            - mountPath: /opt/certs
              name: ca-pair-sslcerts-tls-crt
      volumes:
        - secret:
            defaultMode: 420
            secretName: demo-notification-service-client-properties
          name: demo-notification-service-client-properties
        - secret:
            defaultMode: 420
            secretName: ca-pair-sslcerts
            items:
              - key: tls.crt
                path: ca.pem
          name: ca-pair-sslcerts-tls-crt
